// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ActivateOAuthAppRequest struct {
	// OAuth app ID
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (a *ActivateOAuthAppRequest) GetAppID() string {
	if a == nil {
		return ""
	}
	return a.AppID
}

type ActivateOAuthAppResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth app activated
	OAuthAppResponse *components.OAuthAppResponse
}

func (a ActivateOAuthAppResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActivateOAuthAppResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *ActivateOAuthAppResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *ActivateOAuthAppResponse) GetOAuthAppResponse() *components.OAuthAppResponse {
	if a == nil {
		return nil
	}
	return a.OAuthAppResponse
}
