// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type AddMessageStreamRequest struct {
	// Identifier of the conversation to append the message to. The
	// conversation must belong to the caller and must not be deleted.
	//
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body components.AddMessageRequest `request:"mediaType=application/json"`
}

func (a *AddMessageStreamRequest) GetConversationID() string {
	if a == nil {
		return ""
	}
	return a.ConversationID
}

func (a *AddMessageStreamRequest) GetBody() components.AddMessageRequest {
	if a == nil {
		return components.AddMessageRequest{}
	}
	return a.Body
}

type AddMessageStreamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established. The body is a sequence of
	// `text/event-stream` frames using the event vocabulary described
	// on the schema below.
	//
	AssistantMessageStreamSSEEvent *stream.EventStream[components.AssistantMessageStreamSSEEvent]
}

func (a *AddMessageStreamResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddMessageStreamResponse) GetAssistantMessageStreamSSEEvent() *stream.EventStream[components.AssistantMessageStreamSSEEvent] {
	if a == nil {
		return nil
	}
	return a.AssistantMessageStreamSSEEvent
}
