// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// AddUsersToTeamRequestBody - Request payload
type AddUsersToTeamRequestBody struct {
	UserIds []string `json:"userIds,omitzero"`
}

func (a AddUsersToTeamRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddUsersToTeamRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddUsersToTeamRequestBody) GetUserIds() []string {
	if a == nil {
		return nil
	}
	return a.UserIds
}

type AddUsersToTeamRequest struct {
	TeamID string `pathParam:"style=simple,explode=false,name=teamId"`
	// Request payload
	Body AddUsersToTeamRequestBody `request:"mediaType=application/json"`
}

func (a *AddUsersToTeamRequest) GetTeamID() string {
	if a == nil {
		return ""
	}
	return a.TeamID
}

func (a *AddUsersToTeamRequest) GetBody() AddUsersToTeamRequestBody {
	if a == nil {
		return AddUsersToTeamRequestBody{}
	}
	return a.Body
}

// AddUsersToTeamResponseBody - Users added to team successfully
type AddUsersToTeamResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (a *AddUsersToTeamResponseBody) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

type AddUsersToTeamResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Users added to team successfully
	Object *AddUsersToTeamResponseBody
}

func (a AddUsersToTeamResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AddUsersToTeamResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AddUsersToTeamResponse) GetHTTPMeta() components.HTTPMetadata {
	if a == nil {
		return components.HTTPMetadata{}
	}
	return a.HTTPMeta
}

func (a *AddUsersToTeamResponse) GetObject() *AddUsersToTeamResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
