// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// BulkInviteUsersRequest - Request payload
type BulkInviteUsersRequest struct {
	// Array of email addresses to invite (max 100)
	Emails []string `json:"emails"`
	// Optional group IDs to add all invited users to
	GroupIds []string `json:"groupIds,omitzero"`
	// Whether to send invitation emails immediately
	SendEmail *bool `default:"true" json:"sendEmail"`
}

func (b BulkInviteUsersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkInviteUsersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkInviteUsersRequest) GetEmails() []string {
	if b == nil {
		return []string{}
	}
	return b.Emails
}

func (b *BulkInviteUsersRequest) GetGroupIds() []string {
	if b == nil {
		return nil
	}
	return b.GroupIds
}

func (b *BulkInviteUsersRequest) GetSendEmail() *bool {
	if b == nil {
		return nil
	}
	return b.SendEmail
}

type Failure struct {
	Email  *string `json:"email,omitzero"`
	Reason *string `json:"reason,omitzero"`
}

func (f *Failure) GetEmail() *string {
	if f == nil {
		return nil
	}
	return f.Email
}

func (f *Failure) GetReason() *string {
	if f == nil {
		return nil
	}
	return f.Reason
}

// BulkInviteUsersResponseBody - Bulk invitation processed
type BulkInviteUsersResponseBody struct {
	Success *bool   `json:"success,omitzero"`
	Message *string `json:"message,omitzero"`
	// Number of successful invitations sent
	Invited *int64 `json:"invited,omitzero"`
	// Number of existing users skipped
	Skipped *int64 `json:"skipped,omitzero"`
	// Number of failed invitations
	Failed *int64 `json:"failed,omitzero"`
	// Details of failed invitations
	Failures []Failure `json:"failures,omitzero"`
}

func (b BulkInviteUsersResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkInviteUsersResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkInviteUsersResponseBody) GetSuccess() *bool {
	if b == nil {
		return nil
	}
	return b.Success
}

func (b *BulkInviteUsersResponseBody) GetMessage() *string {
	if b == nil {
		return nil
	}
	return b.Message
}

func (b *BulkInviteUsersResponseBody) GetInvited() *int64 {
	if b == nil {
		return nil
	}
	return b.Invited
}

func (b *BulkInviteUsersResponseBody) GetSkipped() *int64 {
	if b == nil {
		return nil
	}
	return b.Skipped
}

func (b *BulkInviteUsersResponseBody) GetFailed() *int64 {
	if b == nil {
		return nil
	}
	return b.Failed
}

func (b *BulkInviteUsersResponseBody) GetFailures() []Failure {
	if b == nil {
		return nil
	}
	return b.Failures
}

type BulkInviteUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Bulk invitation processed
	Object *BulkInviteUsersResponseBody
}

func (b BulkInviteUsersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *BulkInviteUsersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *BulkInviteUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if b == nil {
		return components.HTTPMetadata{}
	}
	return b.HTTPMeta
}

func (b *BulkInviteUsersResponse) GetObject() *BulkInviteUsersResponseBody {
	if b == nil {
		return nil
	}
	return b.Object
}
