// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CheckOrgExistsResponseBody - Organization existence check completed
type CheckOrgExistsResponseBody struct {
	// Whether an organization has been created
	Exists *bool `json:"exists,omitzero"`
}

func (c *CheckOrgExistsResponseBody) GetExists() *bool {
	if c == nil {
		return nil
	}
	return c.Exists
}

type CheckOrgExistsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Organization existence check completed
	Object *CheckOrgExistsResponseBody
}

func (c CheckOrgExistsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CheckOrgExistsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CheckOrgExistsResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CheckOrgExistsResponse) GetObject() *CheckOrgExistsResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
