// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type CheckToolsetStatusRequest struct {
	ToolsetID string `pathParam:"style=simple,explode=false,name=toolsetId"`
}

func (c *CheckToolsetStatusRequest) GetToolsetID() string {
	if c == nil {
		return ""
	}
	return c.ToolsetID
}

type CheckToolsetStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *CheckToolsetStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
