// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CreateSlackBotConfigRequest - Request payload
type CreateSlackBotConfigRequest struct {
}

// CreateSlackBotConfigResponseBody - Slack bot config created
type CreateSlackBotConfigResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (c *CreateSlackBotConfigResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

type CreateSlackBotConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Slack bot config created
	Object *CreateSlackBotConfigResponseBody
}

func (c CreateSlackBotConfigResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSlackBotConfigResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSlackBotConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSlackBotConfigResponse) GetObject() *CreateSlackBotConfigResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
