// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CreateUserRequest - Request payload
type CreateUserRequest struct {
	// User's full display name
	FullName string `json:"fullName"`
	// User's email address (must be unique)
	Email string `json:"email"`
	// Mobile phone number with country code
	Mobile *string `json:"mobile,omitzero"`
	// Job title or designation
	Designation *string `json:"designation,omitzero"`
	// Whether to send invitation email immediately
	SendInvite *bool `default:"true" json:"sendInvite"`
}

func (c CreateUserRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserRequest) GetFullName() string {
	if c == nil {
		return ""
	}
	return c.FullName
}

func (c *CreateUserRequest) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

func (c *CreateUserRequest) GetMobile() *string {
	if c == nil {
		return nil
	}
	return c.Mobile
}

func (c *CreateUserRequest) GetDesignation() *string {
	if c == nil {
		return nil
	}
	return c.Designation
}

func (c *CreateUserRequest) GetSendInvite() *bool {
	if c == nil {
		return nil
	}
	return c.SendInvite
}

// CreateUserResponseBody - User created successfully
type CreateUserResponseBody struct {
	Success *bool   `json:"success,omitzero"`
	Message *string `json:"message,omitzero"`
	// User account in an organization
	Data *components.User `json:"data,omitzero"`
	// Whether invitation email was sent
	InviteSent *bool `json:"inviteSent,omitzero"`
}

func (c CreateUserResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponseBody) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

func (c *CreateUserResponseBody) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateUserResponseBody) GetData() *components.User {
	if c == nil {
		return nil
	}
	return c.Data
}

func (c *CreateUserResponseBody) GetInviteSent() *bool {
	if c == nil {
		return nil
	}
	return c.InviteSent
}

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User created successfully
	Object *CreateUserResponseBody
}

func (c CreateUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUserResponse) GetObject() *CreateUserResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
