// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type CreateSMTPConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *CreateSMTPConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
