// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CreateSubfolderRequestBody - Request payload
type CreateSubfolderRequestBody struct {
	FolderName string `json:"folderName"`
}

func (c *CreateSubfolderRequestBody) GetFolderName() string {
	if c == nil {
		return ""
	}
	return c.FolderName
}

type CreateSubfolderRequest struct {
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Parent folder ID
	FolderID string `pathParam:"style=simple,explode=false,name=folderId"`
	// Request payload
	Body CreateSubfolderRequestBody `request:"mediaType=application/json"`
}

func (c *CreateSubfolderRequest) GetKbID() string {
	if c == nil {
		return ""
	}
	return c.KbID
}

func (c *CreateSubfolderRequest) GetFolderID() string {
	if c == nil {
		return ""
	}
	return c.FolderID
}

func (c *CreateSubfolderRequest) GetBody() CreateSubfolderRequestBody {
	if c == nil {
		return CreateSubfolderRequestBody{}
	}
	return c.Body
}

type CreateSubfolderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Subfolder created
	Folder *components.Folder
}

func (c CreateSubfolderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateSubfolderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateSubfolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateSubfolderResponse) GetFolder() *components.Folder {
	if c == nil {
		return nil
	}
	return c.Folder
}
