// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// CreateRootFolderRequestBody - Request payload
type CreateRootFolderRequestBody struct {
	// Name of the folder
	FolderName string `json:"folderName"`
}

func (c *CreateRootFolderRequestBody) GetFolderName() string {
	if c == nil {
		return ""
	}
	return c.FolderName
}

type CreateRootFolderRequest struct {
	// Knowledge base ID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Request payload
	Body CreateRootFolderRequestBody `request:"mediaType=application/json"`
}

func (c *CreateRootFolderRequest) GetKbID() string {
	if c == nil {
		return ""
	}
	return c.KbID
}

func (c *CreateRootFolderRequest) GetBody() CreateRootFolderRequestBody {
	if c == nil {
		return CreateRootFolderRequestBody{}
	}
	return c.Body
}

type CreateRootFolderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Folder created successfully
	Folder *components.Folder
}

func (c CreateRootFolderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateRootFolderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateRootFolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateRootFolderResponse) GetFolder() *components.Folder {
	if c == nil {
		return nil
	}
	return c.Folder
}
