// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type CreateToolsetInstanceRequest struct {
	InstanceName      string         `json:"instanceName"`
	ToolsetType       string         `json:"toolsetType"`
	AuthType          string         `json:"authType"`
	AuthConfig        map[string]any `json:"authConfig,omitzero"`
	BaseURL           *string        `json:"baseUrl,omitzero"`
	OauthConfigID     *string        `json:"oauthConfigId,omitzero"`
	OauthInstanceName *string        `json:"oauthInstanceName,omitzero"`
}

func (c CreateToolsetInstanceRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateToolsetInstanceRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateToolsetInstanceRequest) GetInstanceName() string {
	if c == nil {
		return ""
	}
	return c.InstanceName
}

func (c *CreateToolsetInstanceRequest) GetToolsetType() string {
	if c == nil {
		return ""
	}
	return c.ToolsetType
}

func (c *CreateToolsetInstanceRequest) GetAuthType() string {
	if c == nil {
		return ""
	}
	return c.AuthType
}

func (c *CreateToolsetInstanceRequest) GetAuthConfig() map[string]any {
	if c == nil {
		return nil
	}
	return c.AuthConfig
}

func (c *CreateToolsetInstanceRequest) GetBaseURL() *string {
	if c == nil {
		return nil
	}
	return c.BaseURL
}

func (c *CreateToolsetInstanceRequest) GetOauthConfigID() *string {
	if c == nil {
		return nil
	}
	return c.OauthConfigID
}

func (c *CreateToolsetInstanceRequest) GetOauthInstanceName() *string {
	if c == nil {
		return nil
	}
	return c.OauthInstanceName
}

type CreateToolsetInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (c *CreateToolsetInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}
