// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteToolsetInstanceRequest struct {
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceId"`
}

func (d *DeleteToolsetInstanceRequest) GetInstanceID() string {
	if d == nil {
		return ""
	}
	return d.InstanceID
}

type DeleteToolsetInstanceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteToolsetInstanceResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
