// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// Confirm - Must be "DELETE" to confirm deletion
type Confirm string

const (
	ConfirmDelete Confirm = "DELETE"
)

func (e Confirm) ToPointer() *Confirm {
	return &e
}
func (e *Confirm) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DELETE":
		*e = Confirm(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Confirm: %v", v)
	}
}

type DeleteOrganizationRequest struct {
	// Must be "DELETE" to confirm deletion
	Confirm Confirm `queryParam:"style=form,explode=true,name=confirm"`
}

func (d *DeleteOrganizationRequest) GetConfirm() Confirm {
	if d == nil {
		return Confirm("")
	}
	return d.Confirm
}

// DeleteOrganizationResponseBody - Organization deleted successfully
type DeleteOrganizationResponseBody struct {
	Success *bool   `json:"success,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (d *DeleteOrganizationResponseBody) GetSuccess() *bool {
	if d == nil {
		return nil
	}
	return d.Success
}

func (d *DeleteOrganizationResponseBody) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

type DeleteOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Organization deleted successfully
	Object *DeleteOrganizationResponseBody
}

func (d DeleteOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DeleteOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DeleteOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DeleteOrganizationResponse) GetObject() *DeleteOrganizationResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
