// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteAIModelProviderRequest struct {
	// Type of AI model
	ModelType components.ModelType `pathParam:"style=simple,explode=false,name=modelType"`
	ModelKey  string               `pathParam:"style=simple,explode=false,name=modelKey"`
}

func (d *DeleteAIModelProviderRequest) GetModelType() components.ModelType {
	if d == nil {
		return components.ModelType("")
	}
	return d.ModelType
}

func (d *DeleteAIModelProviderRequest) GetModelKey() string {
	if d == nil {
		return ""
	}
	return d.ModelKey
}

type DeleteAIModelProviderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteAIModelProviderResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
