// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type DeleteRecordRequest struct {
	// Record ID
	RecordID string `pathParam:"style=simple,explode=false,name=recordId"`
}

func (d *DeleteRecordRequest) GetRecordID() string {
	if d == nil {
		return ""
	}
	return d.RecordID
}

type DeleteRecordResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteRecordResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
