// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetAllUsersRequest struct {
	// Page number for pagination (1-based)
	Page *int64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// Number of users per page
	Limit *int64 `default:"50" queryParam:"style=form,explode=true,name=limit"`
	// Search users by name or email
	Search *string `queryParam:"style=form,explode=true,name=search"`
}

func (g GetAllUsersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllUsersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllUsersRequest) GetPage() *int64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetAllUsersRequest) GetLimit() *int64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetAllUsersRequest) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

type GetAllUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of users retrieved successfully
	Users []components.User
}

func (g GetAllUsersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAllUsersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAllUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAllUsersResponse) GetUsers() []components.User {
	if g == nil {
		return nil
	}
	return g.Users
}
