// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetAuthMethodsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authentication methods retrieved successfully
	AuthConfig *components.AuthConfig
}

func (g GetAuthMethodsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAuthMethodsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetAuthMethodsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetAuthMethodsResponse) GetAuthConfig() *components.AuthConfig {
	if g == nil {
		return nil
	}
	return g.AuthConfig
}
