// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetConnectorSchemaRequest struct {
	// Connector type identifier
	ConnectorType string `pathParam:"style=simple,explode=false,name=connectorType"`
}

func (g *GetConnectorSchemaRequest) GetConnectorType() string {
	if g == nil {
		return ""
	}
	return g.ConnectorType
}

// GetConnectorSchemaResponseBody - Schema retrieved
type GetConnectorSchemaResponseBody struct {
	Success *bool `json:"success,omitzero"`
	// Schema definition for configuring a connector type
	Schema *components.ConnectorSchema `json:"schema,omitzero"`
}

func (g GetConnectorSchemaResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConnectorSchemaResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetConnectorSchemaResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetConnectorSchemaResponseBody) GetSchema() *components.ConnectorSchema {
	if g == nil {
		return nil
	}
	return g.Schema
}

type GetConnectorSchemaResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Schema retrieved
	Object *GetConnectorSchemaResponseBody
}

func (g GetConnectorSchemaResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConnectorSchemaResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetConnectorSchemaResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetConnectorSchemaResponse) GetObject() *GetConnectorSchemaResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
