// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetCustomSystemPromptResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// System prompt retrieved
	CustomSystemPrompt *components.CustomSystemPrompt
}

func (g GetCustomSystemPromptResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomSystemPromptResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomSystemPromptResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCustomSystemPromptResponse) GetCustomSystemPrompt() *components.CustomSystemPrompt {
	if g == nil {
		return nil
	}
	return g.CustomSystemPrompt
}
