// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetConnectorPublicURLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Connector URL retrieved
	URLConfig *components.URLConfig
}

func (g GetConnectorPublicURLResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConnectorPublicURLResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetConnectorPublicURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetConnectorPublicURLResponse) GetURLConfig() *components.URLConfig {
	if g == nil {
		return nil
	}
	return g.URLConfig
}
