// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetCrawlingJobStatusRequest struct {
	// Connector type identifier
	Connector string `pathParam:"style=simple,explode=false,name=connector"`
	// Unique identifier of the connector instance
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
}

func (g *GetCrawlingJobStatusRequest) GetConnector() string {
	if g == nil {
		return ""
	}
	return g.Connector
}

func (g *GetCrawlingJobStatusRequest) GetConnectorID() string {
	if g == nil {
		return ""
	}
	return g.ConnectorID
}

// GetCrawlingJobStatusResponseBody - Job status retrieved successfully
type GetCrawlingJobStatusResponseBody struct {
	Success *bool   `json:"success,omitzero"`
	Message *string `json:"message,omitzero"`
	// Complete status information for a crawling job
	Data *components.JobStatus `json:"data,omitzero"`
}

func (g GetCrawlingJobStatusResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCrawlingJobStatusResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCrawlingJobStatusResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetCrawlingJobStatusResponseBody) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetCrawlingJobStatusResponseBody) GetData() *components.JobStatus {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetCrawlingJobStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Job status retrieved successfully
	Object *GetCrawlingJobStatusResponseBody
}

func (g GetCrawlingJobStatusResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCrawlingJobStatusResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCrawlingJobStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetCrawlingJobStatusResponse) GetObject() *GetCrawlingJobStatusResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
