// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetKnowledgeBaseRequest struct {
	// Knowledge base ID
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
}

func (g *GetKnowledgeBaseRequest) GetKbID() string {
	if g == nil {
		return ""
	}
	return g.KbID
}

type GetKnowledgeBaseResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful operation
	KnowledgeBase *components.KnowledgeBase
}

func (g GetKnowledgeBaseResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetKnowledgeBaseResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetKnowledgeBaseResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetKnowledgeBaseResponse) GetKnowledgeBase() *components.KnowledgeBase {
	if g == nil {
		return nil
	}
	return g.KnowledgeBase
}
