// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetOAuthConfigRequest struct {
	ConnectorType string `pathParam:"style=simple,explode=false,name=connectorType"`
	ConfigID      string `pathParam:"style=simple,explode=false,name=configId"`
}

func (g *GetOAuthConfigRequest) GetConnectorType() string {
	if g == nil {
		return ""
	}
	return g.ConnectorType
}

func (g *GetOAuthConfigRequest) GetConfigID() string {
	if g == nil {
		return ""
	}
	return g.ConfigID
}

// GetOAuthConfigResponseBody - OAuth configuration retrieved
type GetOAuthConfigResponseBody struct {
	Success *bool `json:"success,omitzero"`
	// OAuth configuration for a connector type. Created by admins to enable
	// OAuth authentication for connectors.
	//
	OauthConfig *components.OAuthConfig `json:"oauthConfig,omitzero"`
}

func (g GetOAuthConfigResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthConfigResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOAuthConfigResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetOAuthConfigResponseBody) GetOauthConfig() *components.OAuthConfig {
	if g == nil {
		return nil
	}
	return g.OauthConfig
}

type GetOAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth configuration retrieved
	Object *GetOAuthConfigResponseBody
}

func (g GetOAuthConfigResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthConfigResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOAuthConfigResponse) GetObject() *GetOAuthConfigResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
