// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// GetOrganizationLogoResponseBody - Logo URL retrieved successfully
type GetOrganizationLogoResponseBody struct {
	Success *bool `json:"success,omitzero"`
	// Whether organization has a custom logo
	HasLogo *bool `json:"hasLogo,omitzero"`
	// Signed URL to access the logo (null if no logo)
	LogoURL *string `json:"logoUrl,omitzero"`
}

func (g *GetOrganizationLogoResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetOrganizationLogoResponseBody) GetHasLogo() *bool {
	if g == nil {
		return nil
	}
	return g.HasLogo
}

func (g *GetOrganizationLogoResponseBody) GetLogoURL() *string {
	if g == nil {
		return nil
	}
	return g.LogoURL
}

type GetOrganizationLogoResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Logo URL retrieved successfully
	Object *GetOrganizationLogoResponseBody
}

func (g GetOrganizationLogoResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOrganizationLogoResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOrganizationLogoResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOrganizationLogoResponse) GetObject() *GetOrganizationLogoResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
