// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetOAuthAppRequest struct {
	// OAuth app ID (MongoDB ObjectId)
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (g *GetOAuthAppRequest) GetAppID() string {
	if g == nil {
		return ""
	}
	return g.AppID
}

type GetOAuthAppResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth app details
	OAuthAppResponse *components.OAuthAppResponse
}

func (g GetOAuthAppResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetOAuthAppResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetOAuthAppResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetOAuthAppResponse) GetOAuthAppResponse() *components.OAuthAppResponse {
	if g == nil {
		return nil
	}
	return g.OAuthAppResponse
}
