// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"time"
)

type GetTokenFromCodeRequest struct {
	// Google OAuth authorization code received from the consent flow
	TempCode string `json:"tempCode"`
}

func (g *GetTokenFromCodeRequest) GetTempCode() string {
	if g == nil {
		return ""
	}
	return g.TempCode
}

type Connector2 struct {
	ID            *string    `json:"_id,omitzero"`
	OrgID         *string    `json:"orgId,omitzero"`
	Name          *string    `json:"name,omitzero"`
	IsEnabled     *bool      `json:"isEnabled,omitzero"`
	LastUpdatedBy *string    `json:"lastUpdatedBy,omitzero"`
	CreatedAt     *time.Time `json:"createdAt,omitzero"`
	UpdatedAt     *time.Time `json:"updatedAt,omitzero"`
}

func (c Connector2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Connector2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Connector2) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *Connector2) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *Connector2) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *Connector2) GetIsEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsEnabled
}

func (c *Connector2) GetLastUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.LastUpdatedBy
}

func (c *Connector2) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Connector2) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

// GetTokenFromCodeResponseBody2 - New connector created and enabled
type GetTokenFromCodeResponseBody2 struct {
	Message   *string     `json:"message,omitzero"`
	Connector *Connector2 `json:"connector,omitzero"`
}

func (g GetTokenFromCodeResponseBody2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTokenFromCodeResponseBody2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTokenFromCodeResponseBody2) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetTokenFromCodeResponseBody2) GetConnector() *Connector2 {
	if g == nil {
		return nil
	}
	return g.Connector
}

type Connector1 struct {
	ID            *string    `json:"_id,omitzero"`
	OrgID         *string    `json:"orgId,omitzero"`
	Name          *string    `json:"name,omitzero"`
	IsEnabled     *bool      `json:"isEnabled,omitzero"`
	LastUpdatedBy *string    `json:"lastUpdatedBy,omitzero"`
	CreatedAt     *time.Time `json:"createdAt,omitzero"`
	UpdatedAt     *time.Time `json:"updatedAt,omitzero"`
}

func (c Connector1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Connector1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Connector1) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *Connector1) GetOrgID() *string {
	if c == nil {
		return nil
	}
	return c.OrgID
}

func (c *Connector1) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *Connector1) GetIsEnabled() *bool {
	if c == nil {
		return nil
	}
	return c.IsEnabled
}

func (c *Connector1) GetLastUpdatedBy() *string {
	if c == nil {
		return nil
	}
	return c.LastUpdatedBy
}

func (c *Connector1) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Connector1) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

// GetTokenFromCodeResponseBody1 - Existing connector enabled successfully
type GetTokenFromCodeResponseBody1 struct {
	Message   *string     `json:"message,omitzero"`
	Connector *Connector1 `json:"connector,omitzero"`
}

func (g GetTokenFromCodeResponseBody1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTokenFromCodeResponseBody1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTokenFromCodeResponseBody1) GetMessage() *string {
	if g == nil {
		return nil
	}
	return g.Message
}

func (g *GetTokenFromCodeResponseBody1) GetConnector() *Connector1 {
	if g == nil {
		return nil
	}
	return g.Connector
}

type GetTokenFromCodeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Existing connector enabled successfully
	TwoHundredApplicationJSONObject *GetTokenFromCodeResponseBody1
	// New connector created and enabled
	TwoHundredAndOneApplicationJSONObject *GetTokenFromCodeResponseBody2
}

func (g GetTokenFromCodeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTokenFromCodeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTokenFromCodeResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetTokenFromCodeResponse) GetTwoHundredApplicationJSONObject() *GetTokenFromCodeResponseBody1 {
	if g == nil {
		return nil
	}
	return g.TwoHundredApplicationJSONObject
}

func (g *GetTokenFromCodeResponse) GetTwoHundredAndOneApplicationJSONObject() *GetTokenFromCodeResponseBody2 {
	if g == nil {
		return nil
	}
	return g.TwoHundredAndOneApplicationJSONObject
}
