// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetToolsetConfigRequest struct {
	ToolsetID string `pathParam:"style=simple,explode=false,name=toolsetId"`
}

func (g *GetToolsetConfigRequest) GetToolsetID() string {
	if g == nil {
		return ""
	}
	return g.ToolsetID
}

type GetToolsetConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (g *GetToolsetConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}
