// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetToolsetInstancesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Instances retrieved successfully
	Object map[string]any
}

func (g GetToolsetInstancesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetToolsetInstancesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetToolsetInstancesResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetToolsetInstancesResponse) GetObject() map[string]any {
	if g == nil {
		return nil
	}
	return g.Object
}
