// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type GetUserTeamsViaUsersData struct {
}

// GetUserTeamsViaUsersResponseBody - User teams retrieved successfully
type GetUserTeamsViaUsersResponseBody struct {
	Success *bool                      `json:"success,omitzero"`
	Data    []GetUserTeamsViaUsersData `json:"data,omitzero"`
}

func (g GetUserTeamsViaUsersResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserTeamsViaUsersResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserTeamsViaUsersResponseBody) GetSuccess() *bool {
	if g == nil {
		return nil
	}
	return g.Success
}

func (g *GetUserTeamsViaUsersResponseBody) GetData() []GetUserTeamsViaUsersData {
	if g == nil {
		return nil
	}
	return g.Data
}

type GetUserTeamsViaUsersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User teams retrieved successfully
	Object *GetUserTeamsViaUsersResponseBody
}

func (g GetUserTeamsViaUsersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetUserTeamsViaUsersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetUserTeamsViaUsersResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetUserTeamsViaUsersResponse) GetObject() *GetUserTeamsViaUsersResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
