// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

var HandleMCPRequestServerList = []string{
	"https://{instance_url}",
}

type JsonrpcRequest string

const (
	JsonrpcRequestTwoDot0 JsonrpcRequest = "2.0"
)

func (e JsonrpcRequest) ToPointer() *JsonrpcRequest {
	return &e
}
func (e *JsonrpcRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "2.0":
		*e = JsonrpcRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JsonrpcRequest: %v", v)
	}
}

type IDRequestType string

const (
	IDRequestTypeStr     IDRequestType = "str"
	IDRequestTypeInteger IDRequestType = "integer"
)

type IDRequest struct {
	Str     *string `queryParam:"inline" union:"member"`
	Integer *int64  `queryParam:"inline" union:"member"`

	Type IDRequestType
}

func CreateIDRequestStr(str string) IDRequest {
	typ := IDRequestTypeStr

	return IDRequest{
		Str:  &str,
		Type: typ,
	}
}

func CreateIDRequestInteger(integer int64) IDRequest {
	typ := IDRequestTypeInteger

	return IDRequest{
		Integer: &integer,
		Type:    typ,
	}
}

func (u *IDRequest) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDRequestTypeStr,
			Value: &str,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDRequestTypeInteger,
			Value: &integer,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for IDRequest", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for IDRequest", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(IDRequestType)
	switch best.Type {
	case IDRequestTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case IDRequestTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for IDRequest", string(data))
}

func (u IDRequest) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	return nil, errors.New("could not marshal union type IDRequest: all fields are null")
}

type Params struct {
}

// HandleMCPRequestRequest - JSON-RPC 2.0 request object
type HandleMCPRequestRequest struct {
	Jsonrpc JsonrpcRequest `json:"jsonrpc"`
	ID      *IDRequest     `json:"id,omitzero"`
	// MCP method (e.g. initialize, tools/list, tools/call)
	Method string  `json:"method"`
	Params *Params `json:"params,omitzero"`
}

func (h HandleMCPRequestRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleMCPRequestRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleMCPRequestRequest) GetJsonrpc() JsonrpcRequest {
	if h == nil {
		return JsonrpcRequest("")
	}
	return h.Jsonrpc
}

func (h *HandleMCPRequestRequest) GetID() *IDRequest {
	if h == nil {
		return nil
	}
	return h.ID
}

func (h *HandleMCPRequestRequest) GetMethod() string {
	if h == nil {
		return ""
	}
	return h.Method
}

func (h *HandleMCPRequestRequest) GetParams() *Params {
	if h == nil {
		return nil
	}
	return h.Params
}

type JsonrpcResponse string

const (
	JsonrpcResponseTwoDot0 JsonrpcResponse = "2.0"
)

func (e JsonrpcResponse) ToPointer() *JsonrpcResponse {
	return &e
}
func (e *JsonrpcResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "2.0":
		*e = JsonrpcResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for JsonrpcResponse: %v", v)
	}
}

type IDResponseType string

const (
	IDResponseTypeStr     IDResponseType = "str"
	IDResponseTypeInteger IDResponseType = "integer"
	IDResponseTypeUnknown IDResponseType = "Unknown"
)

type IDResponse struct {
	Str        *string         `queryParam:"inline" union:"member"`
	Integer    *int64          `queryParam:"inline" union:"member"`
	UnknownRaw json.RawMessage `json:"-" union:"unknown"`

	Type IDResponseType
}

func CreateIDResponseStr(str string) IDResponse {
	typ := IDResponseTypeStr

	return IDResponse{
		Str:  &str,
		Type: typ,
	}
}

func CreateIDResponseInteger(integer int64) IDResponse {
	typ := IDResponseTypeInteger

	return IDResponse{
		Integer: &integer,
		Type:    typ,
	}
}

func CreateIDResponseUnknown(raw json.RawMessage) IDResponse {
	return IDResponse{
		UnknownRaw: raw,
		Type:       IDResponseTypeUnknown,
	}
}

func (u IDResponse) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u IDResponse) IsUnknown() bool {
	return u.Type == IDResponseTypeUnknown
}

func (u *IDResponse) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDResponseTypeStr,
			Value: &str,
		})
	}

	var integer int64 = int64(0)
	if err := utils.UnmarshalJSON(data, &integer, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IDResponseTypeInteger,
			Value: &integer,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = IDResponseTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = IDResponseTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(IDResponseType)
	switch best.Type {
	case IDResponseTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case IDResponseTypeInteger:
		u.Integer = best.Value.(*int64)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = IDResponseTypeUnknown
	return nil
}

func (u IDResponse) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Integer != nil {
		return utils.MarshalJSON(u.Integer, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type IDResponse: all fields are null")
}

type Result struct {
}

type Error struct {
	Code    *int64  `json:"code,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (e *Error) GetCode() *int64 {
	if e == nil {
		return nil
	}
	return e.Code
}

func (e *Error) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

// HandleMCPRequestResponseBody - JSON-RPC 2.0 response
type HandleMCPRequestResponseBody struct {
	Jsonrpc *JsonrpcResponse `json:"jsonrpc,omitzero"`
	ID      *IDResponse      `json:"id,omitzero"`
	Result  *Result          `json:"result,omitzero"`
	Error   *Error           `json:"error,omitzero"`
}

func (h HandleMCPRequestResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleMCPRequestResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleMCPRequestResponseBody) GetJsonrpc() *JsonrpcResponse {
	if h == nil {
		return nil
	}
	return h.Jsonrpc
}

func (h *HandleMCPRequestResponseBody) GetID() *IDResponse {
	if h == nil {
		return nil
	}
	return h.ID
}

func (h *HandleMCPRequestResponseBody) GetResult() *Result {
	if h == nil {
		return nil
	}
	return h.Result
}

func (h *HandleMCPRequestResponseBody) GetError() *Error {
	if h == nil {
		return nil
	}
	return h.Error
}

type HandleMCPRequestResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// JSON-RPC 2.0 response
	Object *HandleMCPRequestResponseBody
}

func (h HandleMCPRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(h, "", false)
}

func (h *HandleMCPRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &h, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (h *HandleMCPRequestResponse) GetHTTPMeta() components.HTTPMetadata {
	if h == nil {
		return components.HTTPMetadata{}
	}
	return h.HTTPMeta
}

func (h *HandleMCPRequestResponse) GetObject() *HandleMCPRequestResponseBody {
	if h == nil {
		return nil
	}
	return h.Object
}
