// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

var JwksServerList = []string{
	"/",
}

type JwksResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// JSON Web Key Set
	Jwks *components.Jwks
}

func (j JwksResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *JwksResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *JwksResponse) GetHTTPMeta() components.HTTPMetadata {
	if j == nil {
		return components.HTTPMetadata{}
	}
	return j.HTTPMeta
}

func (j *JwksResponse) GetJwks() *components.Jwks {
	if j == nil {
		return nil
	}
	return j.Jwks
}
