// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListConfiguredConnectorsRequest struct {
	// Scope determines visibility and access control for connectors:<br>
	// <ul>
	// <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
	// <li><code>personal</code> - Private to the creating user only</li>
	// </ul>
	//
	Scope  *components.ConnectorScope `queryParam:"style=form,explode=true,name=scope"`
	Page   *int64                     `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit  *int64                     `default:"20" queryParam:"style=form,explode=true,name=limit"`
	Search *string                    `queryParam:"style=form,explode=true,name=search"`
}

func (l ListConfiguredConnectorsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfiguredConnectorsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfiguredConnectorsRequest) GetScope() *components.ConnectorScope {
	if l == nil {
		return nil
	}
	return l.Scope
}

func (l *ListConfiguredConnectorsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListConfiguredConnectorsRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListConfiguredConnectorsRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

// ListConfiguredConnectorsResponseBody - Configured connectors retrieved
type ListConfiguredConnectorsResponseBody struct {
	Success    *bool                          `json:"success,omitzero"`
	Connectors []components.ConnectorInstance `json:"connectors,omitzero"`
	// Pagination information for connector lists
	Pagination *components.ConnectorPagination `json:"pagination,omitzero"`
}

func (l ListConfiguredConnectorsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfiguredConnectorsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfiguredConnectorsResponseBody) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListConfiguredConnectorsResponseBody) GetConnectors() []components.ConnectorInstance {
	if l == nil {
		return nil
	}
	return l.Connectors
}

func (l *ListConfiguredConnectorsResponseBody) GetPagination() *components.ConnectorPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListConfiguredConnectorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Configured connectors retrieved
	Object *ListConfiguredConnectorsResponseBody
}

func (l ListConfiguredConnectorsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfiguredConnectorsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfiguredConnectorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListConfiguredConnectorsResponse) GetObject() *ListConfiguredConnectorsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
