// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// ListInactiveConnectorsResponseBody - Inactive connectors retrieved
type ListInactiveConnectorsResponseBody struct {
	Success    *bool                          `json:"success,omitzero"`
	Connectors []components.ConnectorInstance `json:"connectors,omitzero"`
}

func (l ListInactiveConnectorsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInactiveConnectorsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInactiveConnectorsResponseBody) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListInactiveConnectorsResponseBody) GetConnectors() []components.ConnectorInstance {
	if l == nil {
		return nil
	}
	return l.Connectors
}

type ListInactiveConnectorsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Inactive connectors retrieved
	Object *ListInactiveConnectorsResponseBody
}

func (l ListInactiveConnectorsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInactiveConnectorsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInactiveConnectorsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInactiveConnectorsResponse) GetObject() *ListInactiveConnectorsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
