// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListConfiguredToolsetsToolset struct {
}

// ListConfiguredToolsetsResponseBody - Configured toolsets retrieved successfully
type ListConfiguredToolsetsResponseBody struct {
	Toolsets []ListConfiguredToolsetsToolset `json:"toolsets,omitzero"`
}

func (l ListConfiguredToolsetsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfiguredToolsetsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfiguredToolsetsResponseBody) GetToolsets() []ListConfiguredToolsetsToolset {
	if l == nil {
		return nil
	}
	return l.Toolsets
}

type ListConfiguredToolsetsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Configured toolsets retrieved successfully
	Object *ListConfiguredToolsetsResponseBody
}

func (l ListConfiguredToolsetsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListConfiguredToolsetsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListConfiguredToolsetsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListConfiguredToolsetsResponse) GetObject() *ListConfiguredToolsetsResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
