// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListOAuthConfigsByTypeRequest struct {
	ConnectorType string  `pathParam:"style=simple,explode=false,name=connectorType"`
	Page          *int64  `default:"1" queryParam:"style=form,explode=true,name=page"`
	Limit         *int64  `default:"20" queryParam:"style=form,explode=true,name=limit"`
	Search        *string `queryParam:"style=form,explode=true,name=search"`
}

func (l ListOAuthConfigsByTypeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOAuthConfigsByTypeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOAuthConfigsByTypeRequest) GetConnectorType() string {
	if l == nil {
		return ""
	}
	return l.ConnectorType
}

func (l *ListOAuthConfigsByTypeRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

func (l *ListOAuthConfigsByTypeRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListOAuthConfigsByTypeRequest) GetSearch() *string {
	if l == nil {
		return nil
	}
	return l.Search
}

// ListOAuthConfigsByTypeResponseBody - OAuth configurations retrieved
type ListOAuthConfigsByTypeResponseBody struct {
	Success      *bool                    `json:"success,omitzero"`
	OauthConfigs []components.OAuthConfig `json:"oauthConfigs,omitzero"`
	// Pagination information for connector lists
	Pagination *components.ConnectorPagination `json:"pagination,omitzero"`
}

func (l ListOAuthConfigsByTypeResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOAuthConfigsByTypeResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOAuthConfigsByTypeResponseBody) GetSuccess() *bool {
	if l == nil {
		return nil
	}
	return l.Success
}

func (l *ListOAuthConfigsByTypeResponseBody) GetOauthConfigs() []components.OAuthConfig {
	if l == nil {
		return nil
	}
	return l.OauthConfigs
}

func (l *ListOAuthConfigsByTypeResponseBody) GetPagination() *components.ConnectorPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListOAuthConfigsByTypeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth configurations retrieved
	Object *ListOAuthConfigsByTypeResponseBody
}

func (l ListOAuthConfigsByTypeResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOAuthConfigsByTypeResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOAuthConfigsByTypeResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOAuthConfigsByTypeResponse) GetObject() *ListOAuthConfigsByTypeResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
