// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ListOAuthAppTokensRequest struct {
	// OAuth app ID
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
}

func (l *ListOAuthAppTokensRequest) GetAppID() string {
	if l == nil {
		return ""
	}
	return l.AppID
}

type ListOAuthAppTokensResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of tokens
	OAuthTokenListItems []components.OAuthTokenListItem
}

func (l ListOAuthAppTokensResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOAuthAppTokensResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListOAuthAppTokensResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListOAuthAppTokensResponse) GetOAuthTokenListItems() []components.OAuthTokenListItem {
	if l == nil {
		return nil
	}
	return l.OAuthTokenListItems
}
