// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

var OauthProtectedResourceServerList = []string{
	"/",
}

type OauthProtectedResourceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Protected resource metadata
	OAuthProtectedResourceMetadata *components.OAuthProtectedResourceMetadata
}

func (o OauthProtectedResourceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OauthProtectedResourceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OauthProtectedResourceResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OauthProtectedResourceResponse) GetOAuthProtectedResourceMetadata() *components.OAuthProtectedResourceMetadata {
	if o == nil {
		return nil
	}
	return o.OAuthProtectedResourceMetadata
}
