// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type OauthIntrospectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Token introspection result
	OAuthIntrospectResponse *components.OAuthIntrospectResponse
}

func (o OauthIntrospectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OauthIntrospectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OauthIntrospectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OauthIntrospectResponse) GetOAuthIntrospectResponse() *components.OAuthIntrospectResponse {
	if o == nil {
		return nil
	}
	return o.OAuthIntrospectResponse
}
