// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type OauthTokenResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Tokens issued successfully
	OAuthTokenResponse *components.OAuthTokenResponse
}

func (o OauthTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OauthTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OauthTokenResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OauthTokenResponse) GetOAuthTokenResponse() *components.OAuthTokenResponse {
	if o == nil {
		return nil
	}
	return o.OAuthTokenResponse
}
