// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

var OpenidConfigurationServerList = []string{
	"/",
}

type OpenidConfigurationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authorization server metadata
	OpenIDConfiguration *components.OpenIDConfiguration
}

func (o OpenidConfigurationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OpenidConfigurationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OpenidConfigurationResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *OpenidConfigurationResponse) GetOpenIDConfiguration() *components.OpenIDConfiguration {
	if o == nil {
		return nil
	}
	return o.OpenIDConfiguration
}
