// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ReauthenticateToolsetRequest struct {
	ToolsetID string `pathParam:"style=simple,explode=false,name=toolsetId"`
}

func (r *ReauthenticateToolsetRequest) GetToolsetID() string {
	if r == nil {
		return ""
	}
	return r.ToolsetID
}

// ReauthenticateToolsetResponseBody - Reauthentication initiated successfully
type ReauthenticateToolsetResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (r *ReauthenticateToolsetResponseBody) GetMessage() *string {
	if r == nil {
		return nil
	}
	return r.Message
}

type ReauthenticateToolsetResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Reauthentication initiated successfully
	Object *ReauthenticateToolsetResponseBody
}

func (r ReauthenticateToolsetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReauthenticateToolsetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReauthenticateToolsetResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReauthenticateToolsetResponse) GetObject() *ReauthenticateToolsetResponseBody {
	if r == nil {
		return nil
	}
	return r.Object
}
