// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type SaveConnectorFiltersRequest struct {
	ConnectorID string `pathParam:"style=simple,explode=false,name=connectorId"`
	// Request payload
	Body components.SaveConnectorFiltersRequest `request:"mediaType=application/json"`
}

func (s *SaveConnectorFiltersRequest) GetConnectorID() string {
	if s == nil {
		return ""
	}
	return s.ConnectorID
}

func (s *SaveConnectorFiltersRequest) GetBody() components.SaveConnectorFiltersRequest {
	if s == nil {
		return components.SaveConnectorFiltersRequest{}
	}
	return s.Body
}

// SaveConnectorFiltersResponseBody - Filters saved
type SaveConnectorFiltersResponseBody struct {
	Success *bool   `json:"success,omitzero"`
	Message *string `json:"message,omitzero"`
}

func (s *SaveConnectorFiltersResponseBody) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

func (s *SaveConnectorFiltersResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

type SaveConnectorFiltersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Filters saved
	Object *SaveConnectorFiltersResponseBody
}

func (s SaveConnectorFiltersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SaveConnectorFiltersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SaveConnectorFiltersResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SaveConnectorFiltersResponse) GetObject() *SaveConnectorFiltersResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
