// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type SetMicrosoftAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (s *SetMicrosoftAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}
