// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// SetUpAuthConfigRequest - Request payload
type SetUpAuthConfigRequest struct {
}

// SetUpAuthConfigResponseBody - Auth configuration set up successfully
type SetUpAuthConfigResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (s *SetUpAuthConfigResponseBody) GetMessage() *string {
	if s == nil {
		return nil
	}
	return s.Message
}

type SetUpAuthConfigResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Auth configuration set up successfully
	Object *SetUpAuthConfigResponseBody
}

func (s SetUpAuthConfigResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SetUpAuthConfigResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SetUpAuthConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SetUpAuthConfigResponse) GetObject() *SetUpAuthConfigResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
