// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type ShareAgentRequest struct {
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// Request body for Share agent
	Body components.ShareRequest `request:"mediaType=application/json"`
}

func (s *ShareAgentRequest) GetAgentKey() string {
	if s == nil {
		return ""
	}
	return s.AgentKey
}

func (s *ShareAgentRequest) GetBody() components.ShareRequest {
	if s == nil {
		return components.ShareRequest{}
	}
	return s.Body
}

type ShareAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent shared
	Agent *components.Agent
}

func (s ShareAgentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ShareAgentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ShareAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *ShareAgentResponse) GetAgent() *components.Agent {
	if s == nil {
		return nil
	}
	return s.Agent
}
