// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type SignInViaSAMLRequest struct {
	// User's email address
	Email string `queryParam:"style=form,explode=true,name=email"`
	// Session token from `/userAccount/initAuth`. Optional but recommended
	// for maintaining authentication state across the SAML flow.
	//
	SessionToken *string `queryParam:"style=form,explode=true,name=sessionToken"`
}

func (s *SignInViaSAMLRequest) GetEmail() string {
	if s == nil {
		return ""
	}
	return s.Email
}

func (s *SignInViaSAMLRequest) GetSessionToken() *string {
	if s == nil {
		return nil
	}
	return s.SessionToken
}

type SignInViaSAMLResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Headers  map[string][]string
}

func (s *SignInViaSAMLResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *SignInViaSAMLResponse) GetHeaders() map[string][]string {
	if s == nil {
		return map[string][]string{}
	}
	return s.Headers
}
