// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type StreamAgentMessageRequest struct {
	AgentKey       string `pathParam:"style=simple,explode=false,name=agentKey"`
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body components.AddMessageRequest `request:"mediaType=application/json"`
}

func (s *StreamAgentMessageRequest) GetAgentKey() string {
	if s == nil {
		return ""
	}
	return s.AgentKey
}

func (s *StreamAgentMessageRequest) GetConversationID() string {
	if s == nil {
		return ""
	}
	return s.ConversationID
}

func (s *StreamAgentMessageRequest) GetBody() components.AddMessageRequest {
	if s == nil {
		return components.AddMessageRequest{}
	}
	return s.Body
}

type StreamAgentMessageResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established
	SSEEvent *stream.EventStream[components.SSEEvent]
}

func (s *StreamAgentMessageResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StreamAgentMessageResponse) GetSSEEvent() *stream.EventStream[components.SSEEvent] {
	if s == nil {
		return nil
	}
	return s.SSEEvent
}
