// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/types/stream"
)

type StreamAgentConversationRequest struct {
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// Request body for Create agent conversation with streaming
	Body components.CreateConversationRequest `request:"mediaType=application/json"`
}

func (s *StreamAgentConversationRequest) GetAgentKey() string {
	if s == nil {
		return ""
	}
	return s.AgentKey
}

func (s *StreamAgentConversationRequest) GetBody() components.CreateConversationRequest {
	if s == nil {
		return components.CreateConversationRequest{}
	}
	return s.Body
}

type StreamAgentConversationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// SSE stream established
	SSEEvent *stream.EventStream[components.SSEEvent]
}

func (s *StreamAgentConversationResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StreamAgentConversationResponse) GetSSEEvent() *stream.EventStream[components.SSEEvent] {
	if s == nil {
		return nil
	}
	return s.SSEEvent
}
