// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// ToggleMetricsCollectionRequest - Request payload
type ToggleMetricsCollectionRequest struct {
	// Set to true to enable metrics collection, false to disable
	EnableMetricCollection bool `json:"enableMetricCollection"`
}

func (t *ToggleMetricsCollectionRequest) GetEnableMetricCollection() bool {
	if t == nil {
		return false
	}
	return t.EnableMetricCollection
}

// ToggleMetricsCollectionResponseBody - Metrics collection toggled successfully
type ToggleMetricsCollectionResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (t *ToggleMetricsCollectionResponseBody) GetMessage() *string {
	if t == nil {
		return nil
	}
	return t.Message
}

type ToggleMetricsCollectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Metrics collection toggled successfully
	Object *ToggleMetricsCollectionResponseBody
}

func (t ToggleMetricsCollectionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToggleMetricsCollectionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToggleMetricsCollectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *ToggleMetricsCollectionResponse) GetObject() *ToggleMetricsCollectionResponseBody {
	if t == nil {
		return nil
	}
	return t.Object
}
