// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type UnblockUserRequest struct {
	// User ID to unblock
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (u *UnblockUserRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

// UnblockUserResponseBody - User unblocked successfully
type UnblockUserResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (u *UnblockUserResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

type UnblockUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User unblocked successfully
	Object *UnblockUserResponseBody
}

func (u UnblockUserResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UnblockUserResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UnblockUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UnblockUserResponse) GetObject() *UnblockUserResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
