// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateFirstNameRequestBody - Request payload
type UpdateFirstNameRequestBody struct {
	FirstName *string `json:"firstName,omitzero"`
}

func (u *UpdateFirstNameRequestBody) GetFirstName() *string {
	if u == nil {
		return nil
	}
	return u.FirstName
}

type UpdateFirstNameRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Request payload
	Body UpdateFirstNameRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateFirstNameRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateFirstNameRequest) GetBody() UpdateFirstNameRequestBody {
	if u == nil {
		return UpdateFirstNameRequestBody{}
	}
	return u.Body
}

// UpdateFirstNameResponseBody - First name updated successfully
type UpdateFirstNameResponseBody struct {
	Message *string `json:"message,omitzero"`
}

func (u *UpdateFirstNameResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

type UpdateFirstNameResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// First name updated successfully
	Object *UpdateFirstNameResponseBody
}

func (u UpdateFirstNameResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateFirstNameResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateFirstNameResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateFirstNameResponse) GetObject() *UpdateFirstNameResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
