// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
	"time"
)

// UpdateConversationTitleRequestBody - Request payload
type UpdateConversationTitleRequestBody struct {
	// New conversation title
	Title string `json:"title"`
}

func (u *UpdateConversationTitleRequestBody) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

type UpdateConversationTitleRequest struct {
	// Unique conversation identifier
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body UpdateConversationTitleRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateConversationTitleRequest) GetConversationID() string {
	if u == nil {
		return ""
	}
	return u.ConversationID
}

func (u *UpdateConversationTitleRequest) GetBody() UpdateConversationTitleRequestBody {
	if u == nil {
		return UpdateConversationTitleRequestBody{}
	}
	return u.Body
}

type UpdateConversationTitleMessageType string

const (
	UpdateConversationTitleMessageTypeUserQuery   UpdateConversationTitleMessageType = "user_query"
	UpdateConversationTitleMessageTypeBotResponse UpdateConversationTitleMessageType = "bot_response"
	UpdateConversationTitleMessageTypeError       UpdateConversationTitleMessageType = "error"
	UpdateConversationTitleMessageTypeFeedback    UpdateConversationTitleMessageType = "feedback"
	UpdateConversationTitleMessageTypeSystem      UpdateConversationTitleMessageType = "system"
)

func (e UpdateConversationTitleMessageType) ToPointer() *UpdateConversationTitleMessageType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdateConversationTitleMessageType) IsExact() bool {
	if e != nil {
		switch *e {
		case "user_query", "bot_response", "error", "feedback", "system":
			return true
		}
	}
	return false
}

type UpdateConversationTitleContentFormat string

const (
	UpdateConversationTitleContentFormatMarkdown UpdateConversationTitleContentFormat = "MARKDOWN"
	UpdateConversationTitleContentFormatJSON     UpdateConversationTitleContentFormat = "JSON"
	UpdateConversationTitleContentFormatHTML     UpdateConversationTitleContentFormat = "HTML"
)

func (e UpdateConversationTitleContentFormat) ToPointer() *UpdateConversationTitleContentFormat {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdateConversationTitleContentFormat) IsExact() bool {
	if e != nil {
		switch *e {
		case "MARKDOWN", "JSON", "HTML":
			return true
		}
	}
	return false
}

type UpdateConversationTitleReferenceDatum struct {
	// Display name shown to the user.
	Name *string `json:"name,omitzero"`
	// Technical identifier (numeric ID, UUID, etc.).
	ID *string `json:"id,omitzero"`
	// Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`).
	Type *string `json:"type,omitzero"`
	// Source application (e.g. `jira`, `confluence`,
	// `sharepoint`, `slack`, `drive`, `gmail`).
	//
	App *string `json:"app,omitzero"`
	// URL to open the item in a browser.
	WebURL *string `json:"webUrl,omitzero"`
	// App-specific fields keyed by name (e.g. `key` for a Jira
	// project, `siteId` for a SharePoint document).
	//
	Metadata map[string]string `json:"metadata,omitzero"`
}

func (u UpdateConversationTitleReferenceDatum) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleReferenceDatum) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleReferenceDatum) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateConversationTitleReferenceDatum) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UpdateConversationTitleReferenceDatum) GetType() *string {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateConversationTitleReferenceDatum) GetApp() *string {
	if u == nil {
		return nil
	}
	return u.App
}

func (u *UpdateConversationTitleReferenceDatum) GetWebURL() *string {
	if u == nil {
		return nil
	}
	return u.WebURL
}

func (u *UpdateConversationTitleReferenceDatum) GetMetadata() map[string]string {
	if u == nil {
		return nil
	}
	return u.Metadata
}

type UpdateConversationTitleAppliedFilters struct {
	Apps []components.AppliedFilterNode `json:"apps,omitzero"`
	Kb   []components.AppliedFilterNode `json:"kb,omitzero"`
}

func (u UpdateConversationTitleAppliedFilters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleAppliedFilters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleAppliedFilters) GetApps() []components.AppliedFilterNode {
	if u == nil {
		return nil
	}
	return u.Apps
}

func (u *UpdateConversationTitleAppliedFilters) GetKb() []components.AppliedFilterNode {
	if u == nil {
		return nil
	}
	return u.Kb
}

type UpdateConversationTitleMetadata struct {
	ProcessingTimeMs *float64 `json:"processingTimeMs,omitzero"`
	ModelVersion     *string  `json:"modelVersion,omitzero"`
	AiTransactionID  *string  `json:"aiTransactionId,omitzero"`
	Reason           *string  `json:"reason,omitzero"`
}

func (u *UpdateConversationTitleMetadata) GetProcessingTimeMs() *float64 {
	if u == nil {
		return nil
	}
	return u.ProcessingTimeMs
}

func (u *UpdateConversationTitleMetadata) GetModelVersion() *string {
	if u == nil {
		return nil
	}
	return u.ModelVersion
}

func (u *UpdateConversationTitleMetadata) GetAiTransactionID() *string {
	if u == nil {
		return nil
	}
	return u.AiTransactionID
}

func (u *UpdateConversationTitleMetadata) GetReason() *string {
	if u == nil {
		return nil
	}
	return u.Reason
}

type UpdateConversationTitleMessage struct {
	ID            string                                `json:"_id"`
	MessageType   UpdateConversationTitleMessageType    `json:"messageType"`
	Content       string                                `json:"content"`
	ContentFormat *UpdateConversationTitleContentFormat `default:"MARKDOWN" json:"contentFormat"`
	// AI confidence in the answer. Present only on
	// `bot_response` messages, and only when the
	// model emitted a trailing confidence block.
	//
	Confidence *string `json:"confidence,omitzero"`
	// References to source documents used in the
	// response, stored as raw citation pointers
	// (not populated on this endpoint).
	//
	Citations         []components.CitationReference `json:"citations"`
	FollowUpQuestions []components.FollowUpQuestion  `json:"followUpQuestions"`
	Feedback          []components.MessageFeedback   `json:"feedback"`
	// Reference IDs surfaced from tool responses,
	// used for follow-up queries.
	//
	ReferenceData []UpdateConversationTitleReferenceDatum `json:"referenceData"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo      *components.ConversationModelInfo      `json:"modelInfo,omitzero"`
	AppliedFilters *UpdateConversationTitleAppliedFilters `json:"appliedFilters,omitzero"`
	Metadata       *UpdateConversationTitleMetadata       `json:"metadata,omitzero"`
	CreatedAt      time.Time                              `json:"createdAt"`
	UpdatedAt      time.Time                              `json:"updatedAt"`
}

func (u UpdateConversationTitleMessage) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleMessage) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleMessage) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateConversationTitleMessage) GetMessageType() UpdateConversationTitleMessageType {
	if u == nil {
		return UpdateConversationTitleMessageType("")
	}
	return u.MessageType
}

func (u *UpdateConversationTitleMessage) GetContent() string {
	if u == nil {
		return ""
	}
	return u.Content
}

func (u *UpdateConversationTitleMessage) GetContentFormat() *UpdateConversationTitleContentFormat {
	if u == nil {
		return nil
	}
	return u.ContentFormat
}

func (u *UpdateConversationTitleMessage) GetConfidence() *string {
	if u == nil {
		return nil
	}
	return u.Confidence
}

func (u *UpdateConversationTitleMessage) GetCitations() []components.CitationReference {
	if u == nil {
		return []components.CitationReference{}
	}
	return u.Citations
}

func (u *UpdateConversationTitleMessage) GetFollowUpQuestions() []components.FollowUpQuestion {
	if u == nil {
		return []components.FollowUpQuestion{}
	}
	return u.FollowUpQuestions
}

func (u *UpdateConversationTitleMessage) GetFeedback() []components.MessageFeedback {
	if u == nil {
		return []components.MessageFeedback{}
	}
	return u.Feedback
}

func (u *UpdateConversationTitleMessage) GetReferenceData() []UpdateConversationTitleReferenceDatum {
	if u == nil {
		return []UpdateConversationTitleReferenceDatum{}
	}
	return u.ReferenceData
}

func (u *UpdateConversationTitleMessage) GetModelInfo() *components.ConversationModelInfo {
	if u == nil {
		return nil
	}
	return u.ModelInfo
}

func (u *UpdateConversationTitleMessage) GetAppliedFilters() *UpdateConversationTitleAppliedFilters {
	if u == nil {
		return nil
	}
	return u.AppliedFilters
}

func (u *UpdateConversationTitleMessage) GetMetadata() *UpdateConversationTitleMetadata {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateConversationTitleMessage) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UpdateConversationTitleMessage) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

// UpdateConversationTitleStatus - Current status of the conversation:
// - `None` — no activity yet
// - `Inprogress` — AI is processing
// - `Complete` — response ready
// - `Failed` — error occurred
type UpdateConversationTitleStatus string

const (
	UpdateConversationTitleStatusNone       UpdateConversationTitleStatus = "None"
	UpdateConversationTitleStatusInprogress UpdateConversationTitleStatus = "Inprogress"
	UpdateConversationTitleStatusComplete   UpdateConversationTitleStatus = "Complete"
	UpdateConversationTitleStatusFailed     UpdateConversationTitleStatus = "Failed"
)

func (e UpdateConversationTitleStatus) ToPointer() *UpdateConversationTitleStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdateConversationTitleStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "None", "Inprogress", "Complete", "Failed":
			return true
		}
	}
	return false
}

type UpdateConversationTitleAccessLevel string

const (
	UpdateConversationTitleAccessLevelRead  UpdateConversationTitleAccessLevel = "read"
	UpdateConversationTitleAccessLevelWrite UpdateConversationTitleAccessLevel = "write"
)

func (e UpdateConversationTitleAccessLevel) ToPointer() *UpdateConversationTitleAccessLevel {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UpdateConversationTitleAccessLevel) IsExact() bool {
	if e != nil {
		switch *e {
		case "read", "write":
			return true
		}
	}
	return false
}

type UpdateConversationTitleSharedWith struct {
	UserID      string                              `json:"userId"`
	AccessLevel *UpdateConversationTitleAccessLevel `default:"read" json:"accessLevel"`
}

func (u UpdateConversationTitleSharedWith) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleSharedWith) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleSharedWith) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpdateConversationTitleSharedWith) GetAccessLevel() *UpdateConversationTitleAccessLevel {
	if u == nil {
		return nil
	}
	return u.AccessLevel
}

type UpdateConversationTitleConversationError struct {
	// Sub-document identifier auto-assigned by MongoDB.
	ID        string  `json:"_id"`
	Message   string  `json:"message"`
	ErrorType *string `json:"errorType,omitzero"`
	// Time the error was recorded. Server-defaulted
	// to `Date.now` when the entry is pushed, so
	// always present.
	//
	Timestamp time.Time `json:"timestamp"`
	MessageID *string   `json:"messageId,omitzero"`
	Stack     *string   `json:"stack,omitzero"`
	// Free-form metadata attached to this error
	// entry (Map of Mixed in the schema).
	//
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (u UpdateConversationTitleConversationError) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleConversationError) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleConversationError) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateConversationTitleConversationError) GetMessage() string {
	if u == nil {
		return ""
	}
	return u.Message
}

func (u *UpdateConversationTitleConversationError) GetErrorType() *string {
	if u == nil {
		return nil
	}
	return u.ErrorType
}

func (u *UpdateConversationTitleConversationError) GetTimestamp() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.Timestamp
}

func (u *UpdateConversationTitleConversationError) GetMessageID() *string {
	if u == nil {
		return nil
	}
	return u.MessageID
}

func (u *UpdateConversationTitleConversationError) GetStack() *string {
	if u == nil {
		return nil
	}
	return u.Stack
}

func (u *UpdateConversationTitleConversationError) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

// UpdateConversationTitleConversation - The full conversation document after the title update,
// returned as stored in MongoDB.
type UpdateConversationTitleConversation struct {
	// Unique conversation identifier
	ID string `json:"_id"`
	// ID of the user who owns this conversation
	UserID string `json:"userId"`
	// Organization this conversation belongs to
	OrgID string `json:"orgId"`
	// Conversation title. Present and equal to the value
	// submitted in the request body after a successful
	// update.
	//
	Title *string `json:"title,omitzero"`
	// User who started the conversation
	Initiator string `json:"initiator"`
	// All messages stored on this conversation.
	Messages []UpdateConversationTitleMessage `json:"messages"`
	// Current status of the conversation:
	// - `None` — no activity yet
	// - `Inprogress` — AI is processing
	// - `Complete` — response ready
	// - `Failed` — error occurred
	//
	Status *UpdateConversationTitleStatus `json:"status,omitzero"`
	// Error description, populated only when `status`
	// is `Failed`.
	//
	FailReason *string `json:"failReason,omitzero"`
	// AI model configuration recorded against a conversation or message.
	ModelInfo *components.ConversationModelInfo `json:"modelInfo,omitzero"`
	// Whether this conversation is shared with others
	IsShared *bool `default:"false" json:"isShared"`
	// Shareable link if the conversation is shared
	ShareLink *string `json:"shareLink,omitzero"`
	// Users this conversation is shared with
	SharedWith []UpdateConversationTitleSharedWith `json:"sharedWith"`
	// Whether this conversation is archived
	IsArchived *bool `default:"false" json:"isArchived"`
	// User ID of the last user who archived this row, or `null` after
	// unarchive cleared the archive state. Absent on rows that have
	// never been archived.
	//
	ArchivedBy optionalnullable.OptionalNullable[string] `json:"archivedBy,omitzero"`
	// Whether this conversation has been soft-deleted.
	IsDeleted *bool `default:"false" json:"isDeleted"`
	// User who soft-deleted this conversation.
	DeletedBy *string `json:"deletedBy,omitzero"`
	// Errors recorded against this conversation
	// (e.g. failed message generations).
	//
	ConversationErrors []UpdateConversationTitleConversationError `json:"conversationErrors"`
	// Free-form metadata attached to the conversation.
	Metadata map[string]any `json:"metadata,omitzero"`
	// Unix timestamp of the last activity, stored as
	// epoch milliseconds (server-side default `Date.now`).
	//
	LastActivityAt int64     `json:"lastActivityAt"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	// Mongoose document version key.
	V int64 `json:"__v"`
}

func (u UpdateConversationTitleConversation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleConversation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleConversation) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateConversationTitleConversation) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpdateConversationTitleConversation) GetOrgID() string {
	if u == nil {
		return ""
	}
	return u.OrgID
}

func (u *UpdateConversationTitleConversation) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateConversationTitleConversation) GetInitiator() string {
	if u == nil {
		return ""
	}
	return u.Initiator
}

func (u *UpdateConversationTitleConversation) GetMessages() []UpdateConversationTitleMessage {
	if u == nil {
		return []UpdateConversationTitleMessage{}
	}
	return u.Messages
}

func (u *UpdateConversationTitleConversation) GetStatus() *UpdateConversationTitleStatus {
	if u == nil {
		return nil
	}
	return u.Status
}

func (u *UpdateConversationTitleConversation) GetFailReason() *string {
	if u == nil {
		return nil
	}
	return u.FailReason
}

func (u *UpdateConversationTitleConversation) GetModelInfo() *components.ConversationModelInfo {
	if u == nil {
		return nil
	}
	return u.ModelInfo
}

func (u *UpdateConversationTitleConversation) GetIsShared() *bool {
	if u == nil {
		return nil
	}
	return u.IsShared
}

func (u *UpdateConversationTitleConversation) GetShareLink() *string {
	if u == nil {
		return nil
	}
	return u.ShareLink
}

func (u *UpdateConversationTitleConversation) GetSharedWith() []UpdateConversationTitleSharedWith {
	if u == nil {
		return []UpdateConversationTitleSharedWith{}
	}
	return u.SharedWith
}

func (u *UpdateConversationTitleConversation) GetIsArchived() *bool {
	if u == nil {
		return nil
	}
	return u.IsArchived
}

func (u *UpdateConversationTitleConversation) GetArchivedBy() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.ArchivedBy
}

func (u *UpdateConversationTitleConversation) GetIsDeleted() *bool {
	if u == nil {
		return nil
	}
	return u.IsDeleted
}

func (u *UpdateConversationTitleConversation) GetDeletedBy() *string {
	if u == nil {
		return nil
	}
	return u.DeletedBy
}

func (u *UpdateConversationTitleConversation) GetConversationErrors() []UpdateConversationTitleConversationError {
	if u == nil {
		return []UpdateConversationTitleConversationError{}
	}
	return u.ConversationErrors
}

func (u *UpdateConversationTitleConversation) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *UpdateConversationTitleConversation) GetLastActivityAt() int64 {
	if u == nil {
		return 0
	}
	return u.LastActivityAt
}

func (u *UpdateConversationTitleConversation) GetCreatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.CreatedAt
}

func (u *UpdateConversationTitleConversation) GetUpdatedAt() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.UpdatedAt
}

func (u *UpdateConversationTitleConversation) GetV() int64 {
	if u == nil {
		return 0
	}
	return u.V
}

type UpdateConversationTitleMeta struct {
	// Server-side request identifier. Read from the
	// `X-Request-ID` header when supplied, otherwise
	// auto-generated, so this field is always present.
	//
	RequestID string    `json:"requestId"`
	Timestamp time.Time `json:"timestamp"`
	// Server-side processing time in milliseconds.
	Duration int64 `json:"duration"`
}

func (u UpdateConversationTitleMeta) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleMeta) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleMeta) GetRequestID() string {
	if u == nil {
		return ""
	}
	return u.RequestID
}

func (u *UpdateConversationTitleMeta) GetTimestamp() time.Time {
	if u == nil {
		return time.Time{}
	}
	return u.Timestamp
}

func (u *UpdateConversationTitleMeta) GetDuration() int64 {
	if u == nil {
		return 0
	}
	return u.Duration
}

// UpdateConversationTitleResponseBody - Title updated successfully
type UpdateConversationTitleResponseBody struct {
	// The full conversation document after the title update,
	// returned as stored in MongoDB.
	//
	Conversation UpdateConversationTitleConversation `json:"conversation"`
	Meta         UpdateConversationTitleMeta         `json:"meta"`
}

func (u *UpdateConversationTitleResponseBody) GetConversation() UpdateConversationTitleConversation {
	if u == nil {
		return UpdateConversationTitleConversation{}
	}
	return u.Conversation
}

func (u *UpdateConversationTitleResponseBody) GetMeta() UpdateConversationTitleMeta {
	if u == nil {
		return UpdateConversationTitleMeta{}
	}
	return u.Meta
}

type UpdateConversationTitleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Title updated successfully
	Object *UpdateConversationTitleResponseBody
}

func (u UpdateConversationTitleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateConversationTitleResponse) GetObject() *UpdateConversationTitleResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
