// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateAuthMethodRequest - Request payload
type UpdateAuthMethodRequest struct {
	// Authentication steps to set for the organization (1-3 steps)
	AuthMethod []components.AuthStep `json:"authMethod"`
}

func (u *UpdateAuthMethodRequest) GetAuthMethod() []components.AuthStep {
	if u == nil {
		return []components.AuthStep{}
	}
	return u.AuthMethod
}

type UpdateAuthMethodResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Authentication methods updated successfully
	UpdateAuthMethodResponse *components.UpdateAuthMethodResponse
}

func (u UpdateAuthMethodResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAuthMethodResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAuthMethodResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAuthMethodResponse) GetUpdateAuthMethodResponse() *components.UpdateAuthMethodResponse {
	if u == nil {
		return nil
	}
	return u.UpdateAuthMethodResponse
}
