// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateOrganizationRequest - Request payload
type UpdateOrganizationRequest struct {
	// Official registered/legal name
	RegisteredName *string `json:"registeredName,omitzero"`
	// Short display name for UI
	ShortName *string `json:"shortName,omitzero"`
	// Contact phone number (international format)
	PhoneNumber      *string             `json:"phoneNumber,omitzero"`
	PermanentAddress *components.Address `json:"permanentAddress,omitzero"`
}

func (u UpdateOrganizationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOrganizationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOrganizationRequest) GetRegisteredName() *string {
	if u == nil {
		return nil
	}
	return u.RegisteredName
}

func (u *UpdateOrganizationRequest) GetShortName() *string {
	if u == nil {
		return nil
	}
	return u.ShortName
}

func (u *UpdateOrganizationRequest) GetPhoneNumber() *string {
	if u == nil {
		return nil
	}
	return u.PhoneNumber
}

func (u *UpdateOrganizationRequest) GetPermanentAddress() *components.Address {
	if u == nil {
		return nil
	}
	return u.PermanentAddress
}

// UpdateOrganizationResponseBody - Organization updated successfully
type UpdateOrganizationResponseBody struct {
	Message *string                  `json:"message,omitzero"`
	Data    *components.Organization `json:"data,omitzero"`
}

func (u UpdateOrganizationResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOrganizationResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOrganizationResponseBody) GetMessage() *string {
	if u == nil {
		return nil
	}
	return u.Message
}

func (u *UpdateOrganizationResponseBody) GetData() *components.Organization {
	if u == nil {
		return nil
	}
	return u.Data
}

type UpdateOrganizationResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Organization updated successfully
	Object *UpdateOrganizationResponseBody
}

func (u UpdateOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateOrganizationResponse) GetObject() *UpdateOrganizationResponseBody {
	if u == nil {
		return nil
	}
	return u.Object
}
