// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

type UpdateAgentModel struct {
	ModelKey    *string `json:"modelKey,omitzero"`
	ModelName   *string `json:"modelName,omitzero"`
	Provider    *string `json:"provider,omitzero"`
	IsReasoning *bool   `json:"isReasoning,omitzero"`
}

func (u UpdateAgentModel) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentModel) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentModel) GetModelKey() *string {
	if u == nil {
		return nil
	}
	return u.ModelKey
}

func (u *UpdateAgentModel) GetModelName() *string {
	if u == nil {
		return nil
	}
	return u.ModelName
}

func (u *UpdateAgentModel) GetProvider() *string {
	if u == nil {
		return nil
	}
	return u.Provider
}

func (u *UpdateAgentModel) GetIsReasoning() *bool {
	if u == nil {
		return nil
	}
	return u.IsReasoning
}

type UpdateAgentModelUnionType string

const (
	UpdateAgentModelUnionTypeStr              UpdateAgentModelUnionType = "str"
	UpdateAgentModelUnionTypeUpdateAgentModel UpdateAgentModelUnionType = "updateAgent_model"
)

type UpdateAgentModelUnion struct {
	Str              *string           `queryParam:"inline" union:"member"`
	UpdateAgentModel *UpdateAgentModel `queryParam:"inline" union:"member"`

	Type UpdateAgentModelUnionType
}

func CreateUpdateAgentModelUnionStr(str string) UpdateAgentModelUnion {
	typ := UpdateAgentModelUnionTypeStr

	return UpdateAgentModelUnion{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpdateAgentModelUnionUpdateAgentModel(updateAgentModel UpdateAgentModel) UpdateAgentModelUnion {
	typ := UpdateAgentModelUnionTypeUpdateAgentModel

	return UpdateAgentModelUnion{
		UpdateAgentModel: &updateAgentModel,
		Type:             typ,
	}
}

func (u *UpdateAgentModelUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateAgentModelUnionTypeStr,
			Value: &str,
		})
	}

	var updateAgentModel UpdateAgentModel = UpdateAgentModel{}
	if err := utils.UnmarshalJSON(data, &updateAgentModel, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateAgentModelUnionTypeUpdateAgentModel,
			Value: &updateAgentModel,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentModelUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentModelUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateAgentModelUnionType)
	switch best.Type {
	case UpdateAgentModelUnionTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case UpdateAgentModelUnionTypeUpdateAgentModel:
		u.UpdateAgentModel = best.Value.(*UpdateAgentModel)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentModelUnion", string(data))
}

func (u UpdateAgentModelUnion) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.UpdateAgentModel != nil {
		return utils.MarshalJSON(u.UpdateAgentModel, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateAgentModelUnion: all fields are null")
}

type UpdateAgentTool struct {
	Name        *string `json:"name,omitzero"`
	FullName    *string `json:"fullName,omitzero"`
	Description *string `json:"description,omitzero"`
}

func (u *UpdateAgentTool) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateAgentTool) GetFullName() *string {
	if u == nil {
		return nil
	}
	return u.FullName
}

func (u *UpdateAgentTool) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

type UpdateAgentToolset struct {
	Name         *string           `json:"name,omitzero"`
	DisplayName  *string           `json:"displayName,omitzero"`
	Type         *string           `json:"type,omitzero"`
	InstanceID   *string           `json:"instanceId,omitzero"`
	InstanceName *string           `json:"instanceName,omitzero"`
	Tools        []UpdateAgentTool `json:"tools,omitzero"`
}

func (u UpdateAgentToolset) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentToolset) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentToolset) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateAgentToolset) GetDisplayName() *string {
	if u == nil {
		return nil
	}
	return u.DisplayName
}

func (u *UpdateAgentToolset) GetType() *string {
	if u == nil {
		return nil
	}
	return u.Type
}

func (u *UpdateAgentToolset) GetInstanceID() *string {
	if u == nil {
		return nil
	}
	return u.InstanceID
}

func (u *UpdateAgentToolset) GetInstanceName() *string {
	if u == nil {
		return nil
	}
	return u.InstanceName
}

func (u *UpdateAgentToolset) GetTools() []UpdateAgentTool {
	if u == nil {
		return nil
	}
	return u.Tools
}

type UpdateAgentFiltersType string

const (
	UpdateAgentFiltersTypeMapOfAny UpdateAgentFiltersType = "mapOfAny"
	UpdateAgentFiltersTypeStr      UpdateAgentFiltersType = "str"
)

type UpdateAgentFilters struct {
	MapOfAny map[string]any `queryParam:"inline" union:"member"`
	Str      *string        `queryParam:"inline" union:"member"`

	Type UpdateAgentFiltersType
}

func CreateUpdateAgentFiltersMapOfAny(mapOfAny map[string]any) UpdateAgentFilters {
	typ := UpdateAgentFiltersTypeMapOfAny

	return UpdateAgentFilters{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateUpdateAgentFiltersStr(str string) UpdateAgentFilters {
	typ := UpdateAgentFiltersTypeStr

	return UpdateAgentFilters{
		Str:  &str,
		Type: typ,
	}
}

func (u *UpdateAgentFilters) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateAgentFiltersTypeMapOfAny,
			Value: mapOfAny,
		})
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateAgentFiltersTypeStr,
			Value: &str,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentFilters", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentFilters", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateAgentFiltersType)
	switch best.Type {
	case UpdateAgentFiltersTypeMapOfAny:
		u.MapOfAny = best.Value.(map[string]any)
		return nil
	case UpdateAgentFiltersTypeStr:
		u.Str = best.Value.(*string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateAgentFilters", string(data))
}

func (u UpdateAgentFilters) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateAgentFilters: all fields are null")
}

type UpdateAgentKnowledge struct {
	ConnectorID *string             `json:"connectorId,omitzero"`
	Filters     *UpdateAgentFilters `json:"filters,omitzero"`
}

func (u *UpdateAgentKnowledge) GetConnectorID() *string {
	if u == nil {
		return nil
	}
	return u.ConnectorID
}

func (u *UpdateAgentKnowledge) GetFilters() *UpdateAgentFilters {
	if u == nil {
		return nil
	}
	return u.Filters
}

// UpdateAgentRequestBody - Request body for Update agent
type UpdateAgentRequestBody struct {
	Name         *string                                   `json:"name,omitzero"`
	Description  *string                                   `json:"description,omitzero"`
	SystemPrompt *string                                   `json:"systemPrompt,omitzero"`
	StartMessage *string                                   `json:"startMessage,omitzero"`
	Instructions optionalnullable.OptionalNullable[string] `json:"instructions,omitzero"`
	Models       []UpdateAgentModelUnion                   `json:"models,omitzero"`
	Toolsets     []UpdateAgentToolset                      `json:"toolsets,omitzero"`
	Knowledge    []UpdateAgentKnowledge                    `json:"knowledge,omitzero"`
	IsPublic     *bool                                     `json:"isPublic,omitzero"`
	ShareWithOrg *bool                                     `json:"shareWithOrg,omitzero"`
}

func (u UpdateAgentRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateAgentRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateAgentRequestBody) GetSystemPrompt() *string {
	if u == nil {
		return nil
	}
	return u.SystemPrompt
}

func (u *UpdateAgentRequestBody) GetStartMessage() *string {
	if u == nil {
		return nil
	}
	return u.StartMessage
}

func (u *UpdateAgentRequestBody) GetInstructions() optionalnullable.OptionalNullable[string] {
	if u == nil {
		return nil
	}
	return u.Instructions
}

func (u *UpdateAgentRequestBody) GetModels() []UpdateAgentModelUnion {
	if u == nil {
		return nil
	}
	return u.Models
}

func (u *UpdateAgentRequestBody) GetToolsets() []UpdateAgentToolset {
	if u == nil {
		return nil
	}
	return u.Toolsets
}

func (u *UpdateAgentRequestBody) GetKnowledge() []UpdateAgentKnowledge {
	if u == nil {
		return nil
	}
	return u.Knowledge
}

func (u *UpdateAgentRequestBody) GetIsPublic() *bool {
	if u == nil {
		return nil
	}
	return u.IsPublic
}

func (u *UpdateAgentRequestBody) GetShareWithOrg() *bool {
	if u == nil {
		return nil
	}
	return u.ShareWithOrg
}

type UpdateAgentRequest struct {
	AgentKey string `pathParam:"style=simple,explode=false,name=agentKey"`
	// Request body for Update agent
	Body UpdateAgentRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateAgentRequest) GetAgentKey() string {
	if u == nil {
		return ""
	}
	return u.AgentKey
}

func (u *UpdateAgentRequest) GetBody() UpdateAgentRequestBody {
	if u == nil {
		return UpdateAgentRequestBody{}
	}
	return u.Body
}

type UpdateAgentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Agent updated
	Agent *components.Agent
}

func (u UpdateAgentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateAgentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateAgentResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateAgentResponse) GetAgent() *components.Agent {
	if u == nil {
		return nil
	}
	return u.Agent
}
