// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type UpdateOAuthAppRequest struct {
	// OAuth app ID
	AppID string `pathParam:"style=simple,explode=false,name=appId"`
	// Request payload
	Body components.UpdateOAuthAppRequest `request:"mediaType=application/json"`
}

func (u *UpdateOAuthAppRequest) GetAppID() string {
	if u == nil {
		return ""
	}
	return u.AppID
}

func (u *UpdateOAuthAppRequest) GetBody() components.UpdateOAuthAppRequest {
	if u == nil {
		return components.UpdateOAuthAppRequest{}
	}
	return u.Body
}

type UpdateOAuthAppResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OAuth app updated
	OAuthAppResponse *components.OAuthAppResponse
}

func (u UpdateOAuthAppResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateOAuthAppResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateOAuthAppResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateOAuthAppResponse) GetOAuthAppResponse() *components.OAuthAppResponse {
	if u == nil {
		return nil
	}
	return u.OAuthAppResponse
}
