// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateConversationTitleRequestBody - Request payload
type UpdateConversationTitleRequestBody struct {
	// New conversation title
	Title string `json:"title"`
}

func (u *UpdateConversationTitleRequestBody) GetTitle() string {
	if u == nil {
		return ""
	}
	return u.Title
}

type UpdateConversationTitleRequest struct {
	ConversationID string `pathParam:"style=simple,explode=false,name=conversationId"`
	// Request payload
	Body UpdateConversationTitleRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateConversationTitleRequest) GetConversationID() string {
	if u == nil {
		return ""
	}
	return u.ConversationID
}

func (u *UpdateConversationTitleRequest) GetBody() UpdateConversationTitleRequestBody {
	if u == nil {
		return UpdateConversationTitleRequestBody{}
	}
	return u.Body
}

type UpdateConversationTitleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Title updated successfully
	Conversation *components.Conversation
}

func (u UpdateConversationTitleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateConversationTitleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateConversationTitleResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateConversationTitleResponse) GetConversation() *components.Conversation {
	if u == nil {
		return nil
	}
	return u.Conversation
}
