// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// UpdateUserGroupRequestBody - Request payload
type UpdateUserGroupRequestBody struct {
	// New display name for the group
	Name *string `json:"name,omitzero"`
	// Updated description
	Description *string `json:"description,omitzero"`
}

func (u *UpdateUserGroupRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateUserGroupRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

type UpdateUserGroupRequest struct {
	// Unique identifier of the user group to update
	GroupID string `pathParam:"style=simple,explode=false,name=groupId"`
	// Request payload
	Body UpdateUserGroupRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateUserGroupRequest) GetGroupID() string {
	if u == nil {
		return ""
	}
	return u.GroupID
}

func (u *UpdateUserGroupRequest) GetBody() UpdateUserGroupRequestBody {
	if u == nil {
		return UpdateUserGroupRequestBody{}
	}
	return u.Body
}

type UpdateUserGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// User group updated successfully
	UserGroup *components.UserGroup
}

func (u UpdateUserGroupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateUserGroupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateUserGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateUserGroupResponse) GetUserGroup() *components.UserGroup {
	if u == nil {
		return nil
	}
	return u.UserGroup
}
