// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
	"io"
)

type UploadUserDisplayPictureFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (u *UploadUserDisplayPictureFile) GetFileName() string {
	if u == nil {
		return ""
	}
	return u.FileName
}

func (u *UploadUserDisplayPictureFile) GetContent() any {
	if u == nil {
		return nil
	}
	return u.Content
}

// UploadUserDisplayPictureRequest - Request payload
type UploadUserDisplayPictureRequest struct {
	// Image file (PNG, JPEG, WebP, or GIF, max 1MB)
	File UploadUserDisplayPictureFile `multipartForm:"file,name=file"`
}

func (u *UploadUserDisplayPictureRequest) GetFile() UploadUserDisplayPictureFile {
	if u == nil {
		return UploadUserDisplayPictureFile{}
	}
	return u.File
}

type UploadUserDisplayPictureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Display picture uploaded
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (u *UploadUserDisplayPictureResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadUserDisplayPictureResponse) GetResponseStream() io.ReadCloser {
	if u == nil {
		return nil
	}
	return u.ResponseStream
}
