// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

type UploadRecordsToFolderFile struct {
	FileName string `multipartForm:"name=fileName"`
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content any `multipartForm:"content"`
}

func (u *UploadRecordsToFolderFile) GetFileName() string {
	if u == nil {
		return ""
	}
	return u.FileName
}

func (u *UploadRecordsToFolderFile) GetContent() any {
	if u == nil {
		return nil
	}
	return u.Content
}

// UploadRecordsToFolderRequestBody - Request payload
type UploadRecordsToFolderRequestBody struct {
	Files []UploadRecordsToFolderFile `multipartForm:"file,name=files"`
	// JSON array with file metadata
	FilesMetadata *string `multipartForm:"name=files_metadata"`
	IsVersioned   *bool   `default:"true" multipartForm:"name=isVersioned"`
}

func (u UploadRecordsToFolderRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadRecordsToFolderRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadRecordsToFolderRequestBody) GetFiles() []UploadRecordsToFolderFile {
	if u == nil {
		return []UploadRecordsToFolderFile{}
	}
	return u.Files
}

func (u *UploadRecordsToFolderRequestBody) GetFilesMetadata() *string {
	if u == nil {
		return nil
	}
	return u.FilesMetadata
}

func (u *UploadRecordsToFolderRequestBody) GetIsVersioned() *bool {
	if u == nil {
		return nil
	}
	return u.IsVersioned
}

type UploadRecordsToFolderRequest struct {
	KbID string `pathParam:"style=simple,explode=false,name=kbId"`
	// Target folder ID
	FolderID string `pathParam:"style=simple,explode=false,name=folderId"`
	// Request payload
	Body UploadRecordsToFolderRequestBody `request:"mediaType=multipart/form-data"`
}

func (u *UploadRecordsToFolderRequest) GetKbID() string {
	if u == nil {
		return ""
	}
	return u.KbID
}

func (u *UploadRecordsToFolderRequest) GetFolderID() string {
	if u == nil {
		return ""
	}
	return u.FolderID
}

func (u *UploadRecordsToFolderRequest) GetBody() UploadRecordsToFolderRequestBody {
	if u == nil {
		return UploadRecordsToFolderRequestBody{}
	}
	return u.Body
}

type UploadRecordsToFolderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Files uploaded successfully
	UploadResult *components.UploadResult
}

func (u UploadRecordsToFolderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UploadRecordsToFolderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UploadRecordsToFolderResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UploadRecordsToFolderResponse) GetUploadResult() *components.UploadResult {
	if u == nil {
		return nil
	}
	return u.UploadResult
}
