// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// AuthMethodType - Type of authentication method:
// - `password`: Email/password authentication
// - `otp`: One-time password via email (6-digit, expires in 10 minutes)
// - `google`: Google OAuth 2.0
// - `microsoft`: Microsoft OAuth 2.0
// - `azureAd`: Azure Active Directory
// - `samlSso`: SAML 2.0 Single Sign-On
// - `oauth`: Generic OAuth 2.0 provider
type AuthMethodType string

const (
	AuthMethodTypeSamlSso   AuthMethodType = "samlSso"
	AuthMethodTypeOtp       AuthMethodType = "otp"
	AuthMethodTypePassword  AuthMethodType = "password"
	AuthMethodTypeGoogle    AuthMethodType = "google"
	AuthMethodTypeMicrosoft AuthMethodType = "microsoft"
	AuthMethodTypeAzureAd   AuthMethodType = "azureAd"
	AuthMethodTypeOauth     AuthMethodType = "oauth"
)

func (e AuthMethodType) ToPointer() *AuthMethodType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *AuthMethodType) IsExact() bool {
	if e != nil {
		switch *e {
		case "samlSso", "otp", "password", "google", "microsoft", "azureAd", "oauth":
			return true
		}
	}
	return false
}

// AuthMethod - Authentication method configuration
type AuthMethod struct {
	// Type of authentication method:
	// - `password`: Email/password authentication
	// - `otp`: One-time password via email (6-digit, expires in 10 minutes)
	// - `google`: Google OAuth 2.0
	// - `microsoft`: Microsoft OAuth 2.0
	// - `azureAd`: Azure Active Directory
	// - `samlSso`: SAML 2.0 Single Sign-On
	// - `oauth`: Generic OAuth 2.0 provider
	//
	Type AuthMethodType `json:"type"`
}

func (a *AuthMethod) GetType() AuthMethodType {
	if a == nil {
		return AuthMethodType("")
	}
	return a.Type
}
