// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type AuthenticateResponseType string

const (
	AuthenticateResponseTypeAuthenticateMultiStepResponse AuthenticateResponseType = "AuthenticateMultiStepResponse"
	AuthenticateResponseTypeAuthenticateFinalResponse     AuthenticateResponseType = "AuthenticateFinalResponse"
	AuthenticateResponseTypeUnknown                       AuthenticateResponseType = "Unknown"
)

// AuthenticateResponse - Either the next step in a multi-factor flow (`status`, `nextStep`, `allowedMethods`, `authProviders`)
// or final tokens (`message`, `accessToken`, `refreshToken`).
type AuthenticateResponse struct {
	AuthenticateMultiStepResponse *AuthenticateMultiStepResponse `queryParam:"inline" union:"member"`
	AuthenticateFinalResponse     *AuthenticateFinalResponse     `queryParam:"inline" union:"member"`
	UnknownRaw                    json.RawMessage                `json:"-" union:"unknown"`

	Type AuthenticateResponseType
}

func CreateAuthenticateResponseAuthenticateMultiStepResponse(authenticateMultiStepResponse AuthenticateMultiStepResponse) AuthenticateResponse {
	typ := AuthenticateResponseTypeAuthenticateMultiStepResponse

	return AuthenticateResponse{
		AuthenticateMultiStepResponse: &authenticateMultiStepResponse,
		Type:                          typ,
	}
}

func CreateAuthenticateResponseAuthenticateFinalResponse(authenticateFinalResponse AuthenticateFinalResponse) AuthenticateResponse {
	typ := AuthenticateResponseTypeAuthenticateFinalResponse

	return AuthenticateResponse{
		AuthenticateFinalResponse: &authenticateFinalResponse,
		Type:                      typ,
	}
}

func CreateAuthenticateResponseUnknown(raw json.RawMessage) AuthenticateResponse {
	return AuthenticateResponse{
		UnknownRaw: raw,
		Type:       AuthenticateResponseTypeUnknown,
	}
}

func (u AuthenticateResponse) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u AuthenticateResponse) IsUnknown() bool {
	return u.Type == AuthenticateResponseTypeUnknown
}

func (u *AuthenticateResponse) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var authenticateMultiStepResponse AuthenticateMultiStepResponse = AuthenticateMultiStepResponse{}
	if err := utils.UnmarshalJSON(data, &authenticateMultiStepResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticateResponseTypeAuthenticateMultiStepResponse,
			Value: &authenticateMultiStepResponse,
		})
	}

	var authenticateFinalResponse AuthenticateFinalResponse = AuthenticateFinalResponse{}
	if err := utils.UnmarshalJSON(data, &authenticateFinalResponse, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  AuthenticateResponseTypeAuthenticateFinalResponse,
			Value: &authenticateFinalResponse,
		})
	}

	if len(candidates) == 0 {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AuthenticateResponseTypeUnknown
		return nil
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AuthenticateResponseTypeUnknown
		return nil
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(AuthenticateResponseType)
	switch best.Type {
	case AuthenticateResponseTypeAuthenticateMultiStepResponse:
		u.AuthenticateMultiStepResponse = best.Value.(*AuthenticateMultiStepResponse)
		return nil
	case AuthenticateResponseTypeAuthenticateFinalResponse:
		u.AuthenticateFinalResponse = best.Value.(*AuthenticateFinalResponse)
		return nil
	}

	u.UnknownRaw = json.RawMessage(data)
	u.Type = AuthenticateResponseTypeUnknown
	return nil
}

func (u AuthenticateResponse) MarshalJSON() ([]byte, error) {
	if u.AuthenticateMultiStepResponse != nil {
		return utils.MarshalJSON(u.AuthenticateMultiStepResponse, "", true)
	}

	if u.AuthenticateFinalResponse != nil {
		return utils.MarshalJSON(u.AuthenticateFinalResponse, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type AuthenticateResponse: all fields are null")
}
