// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// ConnectorScope - Scope determines visibility and access control for connectors:<br>
// <ul>
// <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
// <li><code>personal</code> - Private to the creating user only</li>
// </ul>
type ConnectorScope string

const (
	ConnectorScopeTeam     ConnectorScope = "team"
	ConnectorScopePersonal ConnectorScope = "personal"
)

func (e ConnectorScope) ToPointer() *ConnectorScope {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ConnectorScope) IsExact() bool {
	if e != nil {
		switch *e {
		case "team", "personal":
			return true
		}
	}
	return false
}
