// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// ConnectorFiltersConfigSync - Sync filter selections
type ConnectorFiltersConfigSync struct {
	// Selected filter values (keys are filter field names)
	Values map[string]any `json:"values,omitzero"`
}

func (c ConnectorFiltersConfigSync) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectorFiltersConfigSync) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConnectorFiltersConfigSync) GetValues() map[string]any {
	if c == nil {
		return nil
	}
	return c.Values
}

// Indexing filter selections
type Indexing struct {
	Values map[string]any `json:"values,omitzero"`
}

func (i Indexing) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *Indexing) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *Indexing) GetValues() map[string]any {
	if i == nil {
		return nil
	}
	return i.Values
}

// ConnectorFiltersConfig - Filter configuration to control what data is synced (sync filters and indexing filters)
type ConnectorFiltersConfig struct {
	// Sync filter selections
	Sync *ConnectorFiltersConfigSync `json:"sync,omitzero"`
	// Indexing filter selections
	Indexing *Indexing `json:"indexing,omitzero"`
}

func (c ConnectorFiltersConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ConnectorFiltersConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *ConnectorFiltersConfig) GetSync() *ConnectorFiltersConfigSync {
	if c == nil {
		return nil
	}
	return c.Sync
}

func (c *ConnectorFiltersConfig) GetIndexing() *Indexing {
	if c == nil {
		return nil
	}
	return c.Indexing
}
