// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// ConnectorToggleRequestType - Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
type ConnectorToggleRequestType string

const (
	ConnectorToggleRequestTypeSync  ConnectorToggleRequestType = "sync"
	ConnectorToggleRequestTypeAgent ConnectorToggleRequestType = "agent"
)

func (e ConnectorToggleRequestType) ToPointer() *ConnectorToggleRequestType {
	return &e
}
func (e *ConnectorToggleRequestType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sync":
		fallthrough
	case "agent":
		*e = ConnectorToggleRequestType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectorToggleRequestType: %v", v)
	}
}

// ConnectorToggleRequest - Request to toggle connector active status
type ConnectorToggleRequest struct {
	// Toggle type: 'sync' for data synchronization, 'agent' for AI agent integration
	Type ConnectorToggleRequestType `json:"type"`
}

func (c *ConnectorToggleRequest) GetType() ConnectorToggleRequestType {
	if c == nil {
		return ConnectorToggleRequestType("")
	}
	return c.Type
}
