// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// CustomSystemPrompt - Custom system prompt configuration
type CustomSystemPrompt struct {
	// Custom system prompt text for AI models
	CustomSystemPrompt *string `json:"customSystemPrompt,omitzero"`
}

func (c *CustomSystemPrompt) GetCustomSystemPrompt() *string {
	if c == nil {
		return nil
	}
	return c.CustomSystemPrompt
}
