// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type DailyScheduleConfigScheduleType string

const (
	DailyScheduleConfigScheduleTypeDaily DailyScheduleConfigScheduleType = "daily"
)

func (e DailyScheduleConfigScheduleType) ToPointer() *DailyScheduleConfigScheduleType {
	return &e
}
func (e *DailyScheduleConfigScheduleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "daily":
		*e = DailyScheduleConfigScheduleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DailyScheduleConfigScheduleType: %v", v)
	}
}

// DailyScheduleConfig - Run crawling job once per day at a specified time
type DailyScheduleConfig struct {
	ScheduleType DailyScheduleConfigScheduleType `json:"scheduleType"`
	// Whether the schedule is active. Disabled schedules won't create new jobs.
	IsEnabled *bool `default:"true" json:"isEnabled"`
	// IANA timezone identifier (e.g., "America/New_York", "Europe/London", "Asia/Tokyo")
	Timezone *string `default:"UTC" json:"timezone"`
	// Hour of the day to run (0-23, 24-hour format)
	Hour int64 `json:"hour"`
	// Minute of the hour to run (0-59)
	Minute int64 `json:"minute"`
}

func (d DailyScheduleConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DailyScheduleConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DailyScheduleConfig) GetScheduleType() DailyScheduleConfigScheduleType {
	if d == nil {
		return DailyScheduleConfigScheduleType("")
	}
	return d.ScheduleType
}

func (d *DailyScheduleConfig) GetIsEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.IsEnabled
}

func (d *DailyScheduleConfig) GetTimezone() *string {
	if d == nil {
		return nil
	}
	return d.Timezone
}

func (d *DailyScheduleConfig) GetHour() int64 {
	if d == nil {
		return 0
	}
	return d.Hour
}

func (d *DailyScheduleConfig) GetMinute() int64 {
	if d == nil {
		return 0
	}
	return d.Minute
}
