// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// Filters - App connector instance ids and knowledge-base / record-group ids that narrow retrieval
// for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
// For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
// to let the service use the agent’s stored knowledge and tool configuration. Sending
// `{ "apps": [], "kb": [] }` on an agent stream means **no** knowledge sources for that
// turn (it is not “full org default”).
type Filters struct {
	// Filter by application connector instance IDs
	Apps []string `json:"apps,omitzero"`
	// Filter by knowledge base IDs
	Kb []string `json:"kb,omitzero"`
}

func (f Filters) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(f, "", false)
}

func (f *Filters) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &f, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (f *Filters) GetApps() []string {
	if f == nil {
		return nil
	}
	return f.Apps
}

func (f *Filters) GetKb() []string {
	if f == nil {
		return nil
	}
	return f.Kb
}
