// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// FollowUpQuestion - AI-suggested follow-up question
type FollowUpQuestion struct {
	// The suggested question text
	Question *string `json:"question,omitzero"`
	// Confidence level for this suggestion
	Confidence *string `json:"confidence,omitzero"`
	// Why this question might be relevant
	Reasoning *string `json:"reasoning,omitzero"`
}

func (f *FollowUpQuestion) GetQuestion() *string {
	if f == nil {
		return nil
	}
	return f.Question
}

func (f *FollowUpQuestion) GetConfidence() *string {
	if f == nil {
		return nil
	}
	return f.Confidence
}

func (f *FollowUpQuestion) GetReasoning() *string {
	if f == nil {
		return nil
	}
	return f.Reasoning
}
