// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// GoogleAuthConfig - Google authentication configuration
type GoogleAuthConfig struct {
	// Google OAuth client ID
	ClientID *string `json:"clientId,omitzero"`
}

func (g *GoogleAuthConfig) GetClientID() *string {
	if g == nil {
		return nil
	}
	return g.ClientID
}
