// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

type InitAuthResponseAllowedMethod string

const (
	InitAuthResponseAllowedMethodSamlSso   InitAuthResponseAllowedMethod = "samlSso"
	InitAuthResponseAllowedMethodOtp       InitAuthResponseAllowedMethod = "otp"
	InitAuthResponseAllowedMethodPassword  InitAuthResponseAllowedMethod = "password"
	InitAuthResponseAllowedMethodGoogle    InitAuthResponseAllowedMethod = "google"
	InitAuthResponseAllowedMethodMicrosoft InitAuthResponseAllowedMethod = "microsoft"
	InitAuthResponseAllowedMethodAzureAd   InitAuthResponseAllowedMethod = "azureAd"
	InitAuthResponseAllowedMethodOauth     InitAuthResponseAllowedMethod = "oauth"
)

func (e InitAuthResponseAllowedMethod) ToPointer() *InitAuthResponseAllowedMethod {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InitAuthResponseAllowedMethod) IsExact() bool {
	if e != nil {
		switch *e {
		case "samlSso", "otp", "password", "google", "microsoft", "azureAd", "oauth":
			return true
		}
	}
	return false
}

// InitAuthResponse - Response containing available authentication methods and session info
type InitAuthResponse struct {
	// Current authentication step (0-indexed). Always 0 for initial response.
	CurrentStep *int64 `json:"currentStep,omitzero"`
	// List of allowed authentication methods for the current step
	AllowedMethods []InitAuthResponseAllowedMethod `json:"allowedMethods,omitzero"`
	// Response message
	Message *string `json:"message,omitzero"`
	// Configuration for external authentication providers (returned when those methods are allowed)
	AuthProviders *AuthProviders `json:"authProviders,omitzero"`
}

func (i InitAuthResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *InitAuthResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *InitAuthResponse) GetCurrentStep() *int64 {
	if i == nil {
		return nil
	}
	return i.CurrentStep
}

func (i *InitAuthResponse) GetAllowedMethods() []InitAuthResponseAllowedMethod {
	if i == nil {
		return nil
	}
	return i.AllowedMethods
}

func (i *InitAuthResponse) GetMessage() *string {
	if i == nil {
		return nil
	}
	return i.Message
}

func (i *InitAuthResponse) GetAuthProviders() *AuthProviders {
	if i == nil {
		return nil
	}
	return i.AuthProviders
}
