// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// Jwks - JSON Web Key Set (RFC 7517).
// Contains public keys for verifying token signatures.
type Jwks struct {
	// Array of JSON Web Keys
	Keys []Jwk `json:"keys,omitzero"`
}

func (j Jwks) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(j, "", false)
}

func (j *Jwks) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &j, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (j *Jwks) GetKeys() []Jwk {
	if j == nil {
		return nil
	}
	return j.Keys
}
