// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// UserRoleEnum - User's role in this knowledge base
type UserRoleEnum string

const (
	UserRoleEnumOwner         UserRoleEnum = "OWNER"
	UserRoleEnumOrganizer     UserRoleEnum = "ORGANIZER"
	UserRoleEnumFileorganizer UserRoleEnum = "FILEORGANIZER"
	UserRoleEnumWriter        UserRoleEnum = "WRITER"
	UserRoleEnumCommenter     UserRoleEnum = "COMMENTER"
	UserRoleEnumReader        UserRoleEnum = "READER"
)

func (e UserRoleEnum) ToPointer() *UserRoleEnum {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserRoleEnum) IsExact() bool {
	if e != nil {
		switch *e {
		case "OWNER", "ORGANIZER", "FILEORGANIZER", "WRITER", "COMMENTER", "READER":
			return true
		}
	}
	return false
}

type KnowledgeBase struct {
	// Unique knowledge base identifier
	ID *string `json:"id,omitzero"`
	// Name of the knowledge base
	Name string `json:"name"`
	// Associated connector ID (null for manual KBs)
	ConnectorID optionalnullable.OptionalNullable[string] `json:"connectorId,omitzero"`
	// Creation timestamp in milliseconds
	CreatedAtTimestamp *int64 `json:"createdAtTimestamp,omitzero"`
	// Last update timestamp in milliseconds
	UpdatedAtTimestamp *int64 `json:"updatedAtTimestamp,omitzero"`
	// User ID of the creator
	CreatedBy *string `json:"createdBy,omitzero"`
	// User's role in this knowledge base
	UserRole *UserRoleEnum `json:"userRole,omitzero"`
	// Folders in this knowledge base
	Folders []Folder `json:"folders,omitzero"`
}

func (k KnowledgeBase) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KnowledgeBase) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KnowledgeBase) GetID() *string {
	if k == nil {
		return nil
	}
	return k.ID
}

func (k *KnowledgeBase) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KnowledgeBase) GetConnectorID() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.ConnectorID
}

func (k *KnowledgeBase) GetCreatedAtTimestamp() *int64 {
	if k == nil {
		return nil
	}
	return k.CreatedAtTimestamp
}

func (k *KnowledgeBase) GetUpdatedAtTimestamp() *int64 {
	if k == nil {
		return nil
	}
	return k.UpdatedAtTimestamp
}

func (k *KnowledgeBase) GetCreatedBy() *string {
	if k == nil {
		return nil
	}
	return k.CreatedBy
}

func (k *KnowledgeBase) GetUserRole() *UserRoleEnum {
	if k == nil {
		return nil
	}
	return k.UserRole
}

func (k *KnowledgeBase) GetFolders() []Folder {
	if k == nil {
		return nil
	}
	return k.Folders
}
