// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OAuthExchangeRequest - Request to exchange OAuth authorization code for tokens
type OAuthExchangeRequest struct {
	// OAuth authorization code
	Code string `json:"code"`
	// User email
	Email string `json:"email"`
	// OAuth provider name
	Provider string `json:"provider"`
	// Redirect URI used in authorization request
	RedirectURI string `json:"redirectUri"`
}

func (o *OAuthExchangeRequest) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *OAuthExchangeRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OAuthExchangeRequest) GetProvider() string {
	if o == nil {
		return ""
	}
	return o.Provider
}

func (o *OAuthExchangeRequest) GetRedirectURI() string {
	if o == nil {
		return ""
	}
	return o.RedirectURI
}
