// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"time"
)

// OAuthAppWithSecretStatus - App status
type OAuthAppWithSecretStatus string

const (
	OAuthAppWithSecretStatusActive    OAuthAppWithSecretStatus = "active"
	OAuthAppWithSecretStatusSuspended OAuthAppWithSecretStatus = "suspended"
	OAuthAppWithSecretStatusRevoked   OAuthAppWithSecretStatus = "revoked"
)

func (e OAuthAppWithSecretStatus) ToPointer() *OAuthAppWithSecretStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *OAuthAppWithSecretStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "active", "suspended", "revoked":
			return true
		}
	}
	return false
}

// OAuthAppWithSecret - OAuth app details (without secret)
type OAuthAppWithSecret struct {
	// App ID
	ID *string `json:"id,omitzero"`
	// URL-friendly app slug
	Slug *string `json:"slug,omitzero"`
	// OAuth client ID
	ClientID *string `json:"clientId,omitzero"`
	// App name
	Name *string `json:"name,omitzero"`
	// App description
	Description *string `json:"description,omitzero"`
	// Allowed redirect URIs
	RedirectUris []string `json:"redirectUris,omitzero"`
	// Allowed grant types
	AllowedGrantTypes []string `json:"allowedGrantTypes,omitzero"`
	// Allowed scopes
	AllowedScopes []string `json:"allowedScopes,omitzero"`
	// App status
	Status *OAuthAppWithSecretStatus `json:"status,omitzero"`
	// App logo URL
	LogoURL *string `json:"logoUrl,omitzero"`
	// App homepage
	HomepageURL *string `json:"homepageUrl,omitzero"`
	// Privacy policy URL
	PrivacyPolicyURL *string `json:"privacyPolicyUrl,omitzero"`
	// Terms of service URL
	TermsOfServiceURL *string `json:"termsOfServiceUrl,omitzero"`
	// Whether app is a confidential client
	IsConfidential *bool `json:"isConfidential,omitzero"`
	// Access token lifetime in seconds
	AccessTokenLifetime *int64 `json:"accessTokenLifetime,omitzero"`
	// Refresh token lifetime in seconds
	RefreshTokenLifetime *int64 `json:"refreshTokenLifetime,omitzero"`
	// Creation timestamp
	CreatedAt *time.Time `json:"createdAt,omitzero"`
	// Last update timestamp
	UpdatedAt *time.Time `json:"updatedAt,omitzero"`
	// Client secret (only shown on creation and secret regeneration).
	// Store this securely - it cannot be retrieved later.
	//
	ClientSecret string `json:"clientSecret"`
}

func (o OAuthAppWithSecret) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthAppWithSecret) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthAppWithSecret) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *OAuthAppWithSecret) GetSlug() *string {
	if o == nil {
		return nil
	}
	return o.Slug
}

func (o *OAuthAppWithSecret) GetClientID() *string {
	if o == nil {
		return nil
	}
	return o.ClientID
}

func (o *OAuthAppWithSecret) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *OAuthAppWithSecret) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *OAuthAppWithSecret) GetRedirectUris() []string {
	if o == nil {
		return nil
	}
	return o.RedirectUris
}

func (o *OAuthAppWithSecret) GetAllowedGrantTypes() []string {
	if o == nil {
		return nil
	}
	return o.AllowedGrantTypes
}

func (o *OAuthAppWithSecret) GetAllowedScopes() []string {
	if o == nil {
		return nil
	}
	return o.AllowedScopes
}

func (o *OAuthAppWithSecret) GetStatus() *OAuthAppWithSecretStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *OAuthAppWithSecret) GetLogoURL() *string {
	if o == nil {
		return nil
	}
	return o.LogoURL
}

func (o *OAuthAppWithSecret) GetHomepageURL() *string {
	if o == nil {
		return nil
	}
	return o.HomepageURL
}

func (o *OAuthAppWithSecret) GetPrivacyPolicyURL() *string {
	if o == nil {
		return nil
	}
	return o.PrivacyPolicyURL
}

func (o *OAuthAppWithSecret) GetTermsOfServiceURL() *string {
	if o == nil {
		return nil
	}
	return o.TermsOfServiceURL
}

func (o *OAuthAppWithSecret) GetIsConfidential() *bool {
	if o == nil {
		return nil
	}
	return o.IsConfidential
}

func (o *OAuthAppWithSecret) GetAccessTokenLifetime() *int64 {
	if o == nil {
		return nil
	}
	return o.AccessTokenLifetime
}

func (o *OAuthAppWithSecret) GetRefreshTokenLifetime() *int64 {
	if o == nil {
		return nil
	}
	return o.RefreshTokenLifetime
}

func (o *OAuthAppWithSecret) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *OAuthAppWithSecret) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *OAuthAppWithSecret) GetClientSecret() string {
	if o == nil {
		return ""
	}
	return o.ClientSecret
}
