// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// OAuthRevokeRequestTokenTypeHint - Hint about token type (optional, improves performance)
type OAuthRevokeRequestTokenTypeHint string

const (
	OAuthRevokeRequestTokenTypeHintAccessToken  OAuthRevokeRequestTokenTypeHint = "access_token"
	OAuthRevokeRequestTokenTypeHintRefreshToken OAuthRevokeRequestTokenTypeHint = "refresh_token"
)

func (e OAuthRevokeRequestTokenTypeHint) ToPointer() *OAuthRevokeRequestTokenTypeHint {
	return &e
}
func (e *OAuthRevokeRequestTokenTypeHint) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "access_token":
		fallthrough
	case "refresh_token":
		*e = OAuthRevokeRequestTokenTypeHint(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OAuthRevokeRequestTokenTypeHint: %v", v)
	}
}

// OAuthRevokeRequest - OAuth 2.0 Token Revocation Request (RFC 7009).
// Revokes an access or refresh token.
type OAuthRevokeRequest struct {
	// The token to revoke
	Token string `form:"name=token" json:"token"`
	// Hint about token type (optional, improves performance)
	TokenTypeHint *OAuthRevokeRequestTokenTypeHint `form:"name=token_type_hint" json:"token_type_hint,omitzero"`
	// Client ID
	ClientID string `form:"name=client_id" json:"client_id"`
	// Client secret
	ClientSecret *string `form:"name=client_secret" json:"client_secret,omitzero"`
}

func (o *OAuthRevokeRequest) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *OAuthRevokeRequest) GetTokenTypeHint() *OAuthRevokeRequestTokenTypeHint {
	if o == nil {
		return nil
	}
	return o.TokenTypeHint
}

func (o *OAuthRevokeRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *OAuthRevokeRequest) GetClientSecret() *string {
	if o == nil {
		return nil
	}
	return o.ClientSecret
}
