// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// OAuthCredentials - Credentials for OAuth authentication (Microsoft, Azure AD, generic OAuth)
type OAuthCredentials struct {
	// OAuth access token
	AccessToken string `json:"accessToken"`
	// OAuth ID token (JWT)
	IDToken *string `json:"idToken,omitzero"`
}

func (o OAuthCredentials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(o, "", false)
}

func (o *OAuthCredentials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &o, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *OAuthCredentials) GetAccessToken() string {
	if o == nil {
		return ""
	}
	return o.AccessToken
}

func (o *OAuthCredentials) GetIDToken() *string {
	if o == nil {
		return nil
	}
	return o.IDToken
}
