// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OrgAuthConfigSetupResponse - Response from setting up organization auth configuration
type OrgAuthConfigSetupResponse struct {
	Message string `json:"message"`
}

func (o *OrgAuthConfigSetupResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
