// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// OtpGenerateRequest - Request to generate and send OTP
type OtpGenerateRequest struct {
	// Email address to send OTP to
	Email string `json:"email"`
	// Cloudflare Turnstile CAPTCHA token (optional)
	CfTurnstileResponse *string `json:"cf-turnstile-response,omitzero"`
}

func (o *OtpGenerateRequest) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OtpGenerateRequest) GetCfTurnstileResponse() *string {
	if o == nil {
		return nil
	}
	return o.CfTurnstileResponse
}
