// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
)

// PersistedSemanticSearchCitationMetadata - Citation metadata as persisted in MongoDB. Required fields mirror the
// Mongoose schema's `required: true` flags; the rest are optional and
// may come through as `null` because the AI retrieval service emits
// explicit nulls for absent fields.
type PersistedSemanticSearchCitationMetadata struct {
	OrgID             string                                                                  `json:"orgId"`
	MimeType          string                                                                  `json:"mimeType"`
	RecordID          string                                                                  `json:"recordId"`
	RecordName        string                                                                  `json:"recordName"`
	Origin            string                                                                  `json:"origin"`
	RecordVersion     optionalnullable.OptionalNullable[int64]                                `json:"recordVersion,omitzero"`
	Extension         optionalnullable.OptionalNullable[string]                               `json:"extension,omitzero"`
	WebURL            optionalnullable.OptionalNullable[string]                               `json:"webUrl,omitzero"`
	PreviewRenderable optionalnullable.OptionalNullable[bool]                                 `json:"previewRenderable,omitzero"`
	HideWeburl        optionalnullable.OptionalNullable[bool]                                 `json:"hideWeburl,omitzero"`
	Connector         optionalnullable.OptionalNullable[string]                               `json:"connector,omitzero"`
	RecordType        optionalnullable.OptionalNullable[string]                               `json:"recordType,omitzero"`
	BlockNum          optionalnullable.OptionalNullable[[]*float64]                           `json:"blockNum,omitzero"`
	PageNum           optionalnullable.OptionalNullable[[]*float64]                           `json:"pageNum,omitzero"`
	SheetNum          optionalnullable.OptionalNullable[float64]                              `json:"sheetNum,omitzero"`
	SheetName         optionalnullable.OptionalNullable[string]                               `json:"sheetName,omitzero"`
	BoundingBox       optionalnullable.OptionalNullable[[]PersistedSemanticSearchBoundingBox] `json:"bounding_box,omitzero"`
	BlockType         optionalnullable.OptionalNullable[string]                               `json:"blockType,omitzero"`
	BlockText         optionalnullable.OptionalNullable[string]                               `json:"blockText,omitzero"`
	Departments       optionalnullable.OptionalNullable[[]string]                             `json:"departments,omitzero"`
	Languages         optionalnullable.OptionalNullable[[]string]                             `json:"languages,omitzero"`
	Topics            optionalnullable.OptionalNullable[[]string]                             `json:"topics,omitzero"`
}

func (p PersistedSemanticSearchCitationMetadata) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PersistedSemanticSearchCitationMetadata) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PersistedSemanticSearchCitationMetadata) GetOrgID() string {
	if p == nil {
		return ""
	}
	return p.OrgID
}

func (p *PersistedSemanticSearchCitationMetadata) GetMimeType() string {
	if p == nil {
		return ""
	}
	return p.MimeType
}

func (p *PersistedSemanticSearchCitationMetadata) GetRecordID() string {
	if p == nil {
		return ""
	}
	return p.RecordID
}

func (p *PersistedSemanticSearchCitationMetadata) GetRecordName() string {
	if p == nil {
		return ""
	}
	return p.RecordName
}

func (p *PersistedSemanticSearchCitationMetadata) GetOrigin() string {
	if p == nil {
		return ""
	}
	return p.Origin
}

func (p *PersistedSemanticSearchCitationMetadata) GetRecordVersion() optionalnullable.OptionalNullable[int64] {
	if p == nil {
		return nil
	}
	return p.RecordVersion
}

func (p *PersistedSemanticSearchCitationMetadata) GetExtension() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Extension
}

func (p *PersistedSemanticSearchCitationMetadata) GetWebURL() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.WebURL
}

func (p *PersistedSemanticSearchCitationMetadata) GetPreviewRenderable() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.PreviewRenderable
}

func (p *PersistedSemanticSearchCitationMetadata) GetHideWeburl() optionalnullable.OptionalNullable[bool] {
	if p == nil {
		return nil
	}
	return p.HideWeburl
}

func (p *PersistedSemanticSearchCitationMetadata) GetConnector() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.Connector
}

func (p *PersistedSemanticSearchCitationMetadata) GetRecordType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.RecordType
}

func (p *PersistedSemanticSearchCitationMetadata) GetBlockNum() optionalnullable.OptionalNullable[[]*float64] {
	if p == nil {
		return nil
	}
	return p.BlockNum
}

func (p *PersistedSemanticSearchCitationMetadata) GetPageNum() optionalnullable.OptionalNullable[[]*float64] {
	if p == nil {
		return nil
	}
	return p.PageNum
}

func (p *PersistedSemanticSearchCitationMetadata) GetSheetNum() optionalnullable.OptionalNullable[float64] {
	if p == nil {
		return nil
	}
	return p.SheetNum
}

func (p *PersistedSemanticSearchCitationMetadata) GetSheetName() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.SheetName
}

func (p *PersistedSemanticSearchCitationMetadata) GetBoundingBox() optionalnullable.OptionalNullable[[]PersistedSemanticSearchBoundingBox] {
	if p == nil {
		return nil
	}
	return p.BoundingBox
}

func (p *PersistedSemanticSearchCitationMetadata) GetBlockType() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.BlockType
}

func (p *PersistedSemanticSearchCitationMetadata) GetBlockText() optionalnullable.OptionalNullable[string] {
	if p == nil {
		return nil
	}
	return p.BlockText
}

func (p *PersistedSemanticSearchCitationMetadata) GetDepartments() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Departments
}

func (p *PersistedSemanticSearchCitationMetadata) GetLanguages() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Languages
}

func (p *PersistedSemanticSearchCitationMetadata) GetTopics() optionalnullable.OptionalNullable[[]string] {
	if p == nil {
		return nil
	}
	return p.Topics
}
