// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
	"github.com/pipeshub-ai/pipeshub-sdk-go/optionalnullable"
	"time"
)

// PlatformSettings - Platform-wide configuration settings for file uploads and feature toggles
type PlatformSettings struct {
	// Maximum file upload size in bytes. Default is 30MB (31457280 bytes). Maximum allowed is 1GB.
	FileUploadMaxSizeBytes *int64 `json:"fileUploadMaxSizeBytes,omitzero"`
	// Key-value map of feature flags to enable/disable platform features.
	// Available flags:
	// - ENABLE_BETA_CONNECTORS: Allow usage of beta connector integrations that may be unstable
	//
	FeatureFlags map[string]bool `json:"featureFlags,omitzero"`
	// Timestamp of last settings update (read-only, set automatically). May not be present in the response.
	UpdatedAt optionalnullable.OptionalNullable[time.Time] `json:"updatedAt,omitzero"`
}

func (p PlatformSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PlatformSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PlatformSettings) GetFileUploadMaxSizeBytes() *int64 {
	if p == nil {
		return nil
	}
	return p.FileUploadMaxSizeBytes
}

func (p *PlatformSettings) GetFeatureFlags() map[string]bool {
	if p == nil {
		return nil
	}
	return p.FeatureFlags
}

func (p *PlatformSettings) GetUpdatedAt() optionalnullable.OptionalNullable[time.Time] {
	if p == nil {
		return nil
	}
	return p.UpdatedAt
}
