// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SaveConnectorFiltersRequest - Request to save filter selections for a connector
type SaveConnectorFiltersRequest struct {
	// Filter values to save (structure depends on connector's filter schema)
	Filters map[string]any `json:"filters"`
}

func (s *SaveConnectorFiltersRequest) GetFilters() map[string]any {
	if s == nil {
		return map[string]any{}
	}
	return s.Filters
}
