// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// SearchResultItemMetadata - Additional metadata about the source
type SearchResultItemMetadata struct {
	RecordID      *string `json:"recordId,omitzero"`
	RecordName    *string `json:"recordName,omitzero"`
	ConnectorName *string `json:"connectorName,omitzero"`
	WebURL        *string `json:"webUrl,omitzero"`
	MimeType      *string `json:"mimeType,omitzero"`
}

func (s *SearchResultItemMetadata) GetRecordID() *string {
	if s == nil {
		return nil
	}
	return s.RecordID
}

func (s *SearchResultItemMetadata) GetRecordName() *string {
	if s == nil {
		return nil
	}
	return s.RecordName
}

func (s *SearchResultItemMetadata) GetConnectorName() *string {
	if s == nil {
		return nil
	}
	return s.ConnectorName
}

func (s *SearchResultItemMetadata) GetWebURL() *string {
	if s == nil {
		return nil
	}
	return s.WebURL
}

func (s *SearchResultItemMetadata) GetMimeType() *string {
	if s == nil {
		return nil
	}
	return s.MimeType
}

// SearchResultItem - A single matching chunk from semantic search
type SearchResultItem struct {
	// The matching text content
	Content *string `json:"content,omitzero"`
	// Index of this chunk within the source document
	ChunkIndex *int64 `json:"chunkIndex,omitzero"`
	// Type of citation/source
	CitationType *string `json:"citationType,omitzero"`
	// Additional metadata about the source
	Metadata *SearchResultItemMetadata `json:"metadata,omitzero"`
	// Relevance score (higher is more relevant)
	Score *float64 `json:"score,omitzero"`
}

func (s SearchResultItem) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SearchResultItem) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SearchResultItem) GetContent() *string {
	if s == nil {
		return nil
	}
	return s.Content
}

func (s *SearchResultItem) GetChunkIndex() *int64 {
	if s == nil {
		return nil
	}
	return s.ChunkIndex
}

func (s *SearchResultItem) GetCitationType() *string {
	if s == nil {
		return nil
	}
	return s.CitationType
}

func (s *SearchResultItem) GetMetadata() *SearchResultItemMetadata {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *SearchResultItem) GetScore() *float64 {
	if s == nil {
		return nil
	}
	return s.Score
}
