// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

// SemanticSearchAppliedFilters - Present when KB filters were applied to the search request.
type SemanticSearchAppliedFilters struct {
	Kb      []string `json:"kb"`
	KbCount int64    `json:"kb_count"`
}

func (s *SemanticSearchAppliedFilters) GetKb() []string {
	if s == nil {
		return []string{}
	}
	return s.Kb
}

func (s *SemanticSearchAppliedFilters) GetKbCount() int64 {
	if s == nil {
		return 0
	}
	return s.KbCount
}
