// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// SemanticSearchHistoryFilterToggle - Generic "filter X is available, current value is Y" block used for
// `shared`, `tags`, `minMessages`, `search`, and `messageType`. Either
// `type` (free-form value) or `values` (enum of allowed strings) is
// present, not both. `current` is the caller-supplied value passed
// through from `req.query`, hence string-or-null even when `type` is
// `'number'`.
type SemanticSearchHistoryFilterToggle struct {
	Type        *string  `json:"type,omitzero"`
	Values      []string `json:"values,omitzero"`
	Description string   `json:"description"`
	Current     *string  `json:"current"`
	Applied     bool     `json:"applied"`
}

func (s SemanticSearchHistoryFilterToggle) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SemanticSearchHistoryFilterToggle) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SemanticSearchHistoryFilterToggle) GetType() *string {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *SemanticSearchHistoryFilterToggle) GetValues() []string {
	if s == nil {
		return nil
	}
	return s.Values
}

func (s *SemanticSearchHistoryFilterToggle) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *SemanticSearchHistoryFilterToggle) GetCurrent() *string {
	if s == nil {
		return nil
	}
	return s.Current
}

func (s *SemanticSearchHistoryFilterToggle) GetApplied() bool {
	if s == nil {
		return false
	}
	return s.Applied
}
