// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// SemanticSearchAiResponse - Payload returned by the AI retrieval service for a semantic search (embedded in `searchResponse`).
// Optional `virtual_to_record_map` maps each virtual record id (string key) to one resolved graph record document.
// Empty responses from the retrieval layer omit `virtual_to_record_map`; success payloads may include it alongside hits and records.
type SemanticSearchAiResponse struct {
	SearchResults []SemanticSearchHit         `json:"searchResults"`
	Records       []SemanticSearchGraphRecord `json:"records"`
	Status        string                      `json:"status"`
	StatusCode    int64                       `json:"status_code"`
	Message       string                      `json:"message"`
	// Present when KB filters were applied to the search request.
	AppliedFilters *SemanticSearchAppliedFilters `json:"appliedFilters,omitzero"`
	// Maps virtual record id (object property name) to the accessible graph record document for that id.
	VirtualToRecordMap map[string]SemanticSearchGraphRecord `json:"virtual_to_record_map,omitzero"`
}

func (s SemanticSearchAiResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SemanticSearchAiResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SemanticSearchAiResponse) GetSearchResults() []SemanticSearchHit {
	if s == nil {
		return []SemanticSearchHit{}
	}
	return s.SearchResults
}

func (s *SemanticSearchAiResponse) GetRecords() []SemanticSearchGraphRecord {
	if s == nil {
		return []SemanticSearchGraphRecord{}
	}
	return s.Records
}

func (s *SemanticSearchAiResponse) GetStatus() string {
	if s == nil {
		return ""
	}
	return s.Status
}

func (s *SemanticSearchAiResponse) GetStatusCode() int64 {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *SemanticSearchAiResponse) GetMessage() string {
	if s == nil {
		return ""
	}
	return s.Message
}

func (s *SemanticSearchAiResponse) GetAppliedFilters() *SemanticSearchAppliedFilters {
	if s == nil {
		return nil
	}
	return s.AppliedFilters
}

func (s *SemanticSearchAiResponse) GetVirtualToRecordMap() map[string]SemanticSearchGraphRecord {
	if s == nil {
		return nil
	}
	return s.VirtualToRecordMap
}
