// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type UserBasicAccountType string

const (
	UserBasicAccountTypeIndividual UserBasicAccountType = "individual"
	UserBasicAccountTypeBusiness   UserBasicAccountType = "business"
)

func (e UserBasicAccountType) ToPointer() *UserBasicAccountType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserBasicAccountType) IsExact() bool {
	if e != nil {
		switch *e {
		case "individual", "business":
			return true
		}
	}
	return false
}

// UserBasic - Basic user information
type UserBasic struct {
	// User ID
	ID       *string `json:"_id,omitzero"`
	Email    *string `json:"email,omitzero"`
	FullName *string `json:"fullName,omitzero"`
	// Organization ID
	OrgID       *string               `json:"orgId,omitzero"`
	AccountType *UserBasicAccountType `json:"accountType,omitzero"`
}

func (u *UserBasic) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserBasic) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UserBasic) GetFullName() *string {
	if u == nil {
		return nil
	}
	return u.FullName
}

func (u *UserBasic) GetOrgID() *string {
	if u == nil {
		return nil
	}
	return u.OrgID
}

func (u *UserBasic) GetAccountType() *UserBasicAccountType {
	if u == nil {
		return nil
	}
	return u.AccountType
}
