// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/pipeshub-ai/pipeshub-sdk-go/internal/utils"
)

// UserGroupType - Group type:
// - admin: System admin group (cannot be modified)
// - standard: Default user group
// - everyone: All users group (cannot be modified)
// - custom: User-created custom group
type UserGroupType string

const (
	UserGroupTypeAdmin    UserGroupType = "admin"
	UserGroupTypeStandard UserGroupType = "standard"
	UserGroupTypeEveryone UserGroupType = "everyone"
	UserGroupTypeCustom   UserGroupType = "custom"
)

func (e UserGroupType) ToPointer() *UserGroupType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *UserGroupType) IsExact() bool {
	if e != nil {
		switch *e {
		case "admin", "standard", "everyone", "custom":
			return true
		}
	}
	return false
}

// UserGroup - User group for organizing users within an organization
type UserGroup struct {
	// Unique group identifier
	ID *string `json:"_id,omitzero"`
	// Unique slug for the group
	Slug *string `json:"slug,omitzero"`
	// Group type:
	// - admin: System admin group (cannot be modified)
	// - standard: Default user group
	// - everyone: All users group (cannot be modified)
	// - custom: User-created custom group
	//
	Type UserGroupType `json:"type"`
	// Group name (unique within organization)
	Name string `json:"name"`
	// Organization ID
	OrgID string `json:"orgId"`
	// Array of user IDs in this group
	Users []string `json:"users,omitzero"`
	// Soft delete flag
	IsDeleted *bool `default:"false" json:"isDeleted"`
	// ID of user who deleted this group
	DeletedBy *string `json:"deletedBy,omitzero"`
	// Creation timestamp
	CreatedAt *int64 `json:"createdAt,omitzero"`
	// Last update timestamp
	UpdatedAt *int64 `json:"updatedAt,omitzero"`
}

func (u UserGroup) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UserGroup) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UserGroup) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *UserGroup) GetSlug() *string {
	if u == nil {
		return nil
	}
	return u.Slug
}

func (u *UserGroup) GetType() UserGroupType {
	if u == nil {
		return UserGroupType("")
	}
	return u.Type
}

func (u *UserGroup) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UserGroup) GetOrgID() string {
	if u == nil {
		return ""
	}
	return u.OrgID
}

func (u *UserGroup) GetUsers() []string {
	if u == nil {
		return nil
	}
	return u.Users
}

func (u *UserGroup) GetIsDeleted() *bool {
	if u == nil {
		return nil
	}
	return u.IsDeleted
}

func (u *UserGroup) GetDeletedBy() *string {
	if u == nil {
		return nil
	}
	return u.DeletedBy
}

func (u *UserGroup) GetCreatedAt() *int64 {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *UserGroup) GetUpdatedAt() *int64 {
	if u == nil {
		return nil
	}
	return u.UpdatedAt
}
