// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/pipeshub-ai/pipeshub-sdk-go/models/components"
)

// AuthError - Authentication error response with details for debugging and user feedback.<br><br>
// <b>Common Error Codes:</b><br>
// <ul>
// <li><code>INVALID_CREDENTIALS</code> - Wrong password or OTP</li>
// <li><code>ACCOUNT_BLOCKED</code> - Account locked after 5 failed attempts</li>
// <li><code>SESSION_EXPIRED</code> - Session token has expired</li>
// <li><code>OTP_EXPIRED</code> - OTP code has expired (10 min validity)</li>
// <li><code>USER_NOT_FOUND</code> - Email not registered</li>
// <li><code>INVALID_TOKEN</code> - JWT token is invalid or malformed</li>
// <li><code>METHOD_NOT_ALLOWED</code> - Auth method not enabled for org</li>
// </ul>
type AuthError struct {
	// Error type identifier
	Error_ *string `json:"error,omitzero"`
	// Human-readable error message
	Message *string `json:"message,omitzero"`
	// Error code for programmatic handling
	Code *string `json:"code,omitzero"`
	// HTTP status code
	StatusCode *int64                  `json:"statusCode,omitzero"`
	HTTPMeta   components.HTTPMetadata `json:"-"`
}

var _ error = &AuthError{}

func (e *AuthError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
